### ISSUE TITLE
SoftLimit: avoid single extra line

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1012]
The case of only one extra line is contraproductive as it does not save a single line:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/c754ad07-7a70-4349-aaa8-ec2ba3e5c47d)

**Comment by iloveeclipse** [comment]
Surely we should be more clever, the only problem I see is not from the technical but from API contract point of view.
If we have `setDisplayIncrementally(int incrementSize)` API that currently says:
 
>  If the number of direct children will exceed this limit, the viewer will only show a subset of children up to the limit

So assuming I'm a client of this API and want exact step increment to show max 10 elements at once, but implementation is "clever" and shows 11 elements, this is clearly broken implementation.

So should one change it to `setDisplayIncrementally(int incrementSize, boolean relaxed)` and say 

> if `relaxed` is true, implementation may adopt the number of items shown if the overall number of child items is slightly above the increment value?

@Phillipus : as an early adopter, what would be you expectation for the API?

**Comment by Phillipus** [comment]
Well, "relaxed" is an interesting idea. Would it be a percentage of overall nodes or some other factor?

**Comment by iloveeclipse** [comment]
> Well, "relaxed" is an interesting idea. Would it be a percentage of overall nodes or some other factor?

Depending on what the API would say. It can be anything or nothing at all :-)
I guess some percentage from increment value. So if we have a limit of 10.000 for the input of 500.000 it would be not OK to show percentage from input, because even 10% would be 50.000 more.

I assume people that set increment value for a product (like me) know some real world data size that are "good enough" and set the limit that isn't coming near the "bad" area. So for us (RHEL / GTK3.22) we probably will go with the limit of 10.000 and could easily add "relaxed" 10% - 75% of the limit (1000 - 7500 more elements) without any danger.

In case of 11 elements and limit of 10 that would be exact one more with 10% from limit, but for 12 elements we would still show "10 + 2", so may be 50% is better, it would show 15 elements without extra node 10 and a node for 16.

We might use some other way to calculate the "fuzziness" factor I'm fully open for proposals.

**Comment by laeubi** [comment]
I would more relax the API instead... e.g. 

> If the number of direct children will exceed this limit, the viewer *may* only show a subset of children *based on* the given limit

This will give more freedom to the viewer implementation and maybe one wants to configure different aspects fro different viewer independently, e.g for a tree I maybe want to show *all root nodes* but only a given amount of child nodes depending on the nesting depth.

**Comment by jukzi** [comment]
I don't like the idea of a % relax. A limit is a limit, anything else is confusing. 
Avoiding the single extra line is a very exceptional case of possible optimization.

**Comment by iloveeclipse** [comment]
> A limit is a limit, anything else is confusing.
> Avoiding the single extra line is a very exceptional case of possible optimization.

So we can close this issue? Otherwise I can't understand what is requested.
If a "limit is a limit", then if it is set to 10 elements, 11th element will be not shown.

**Comment by jukzi** [comment]
limit is a limit, but since this special case is so frustrating i suggest to have a 1-element tolerance rule.

**Comment by mickaelistria** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1041 would make this issue less critical or even not relevant.
