### ISSUE TITLE
SoftLimit: improve Preferences Page text/tooltip

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1026]
from https://github.com/eclipse-platform/eclipse.platform.ui/issues/818
1. The preferences page should state that it is a **limit** - that may not take effect on all views. The tooltip may explain that it is also used as increment.
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/ac8b5615-3904-47fb-b669-a6c4bd9dfcc2)
2. Also it is not clear why it says it is a "Default", as i can't see other options that would overrride the default value.
3. A search for the text does not find it:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/caf40751-4988-45b1-b249-b038312889ca)
4. Sad: The Softlimit line itself ignores the option Open Mode= Double click, but also "opens" on Single click. - Double clicking a Softlimit currently selects a random element that unreveald.

**Comment by jukzi** [comment]
5. please add a tooltip that explains a  value of "0" means no limit

**Comment by iloveeclipse** [comment]
> The preferences page should state that it is a limit - that may not take effect on all views

Actually this is both, limit and increment.

> The tooltip may explain that it is also used as increment.

Or the tooltip can explain something different.

It would be nice if you could try to provide your own version of the text / tooltip, so one could see what / how exactly we can improve. We've made few rounds before with the text, no one was happy but no one proposed something where everyone would be happy.

> Also it is not clear why it says it is a "Default", as i can't see other options that would overrride the default value.

It is a workbench default, and every UI might use that or decide for something else, like with different editor settings etc.

> A search for the text does not find it

Once we have something everyone agrees we can add that to the text search.

> Sad: The Softlimit line itself ignores the option Open Mode= Double click, but also "opens" on Single click. - Double clicking a Softlimit currently selects a random element that unreveald.

Not sure why it should be sad. Why should the expandable node be double clicked? We don't double click on "expand" icons in the trees, independently which mode is selected, here is same logic applied.

> please add a tooltip that explains a value of "0" means no limit

Yes, once everyone has agreed on what goes to the text and what on the tooltip text.

**Comment by jukzi** [comment]
Suggestion:
text: `Maximum number of elements shown in views:`
hint: `Use 0 for no limit.  If the number of element is exceeded an extra element is shown that allows to expand more items. Not all views support support this limit. `
searchable words: `limit, maximum, view, elements, items`

**Comment by mickaelistria** [comment]
To be honest, I don't think this preference should even be exposed to users. It's highly technical and not functional. Users just expect things to work, without having to deal with such fine details.

**Comment by iloveeclipse** [comment]
So far we had following attempts / proposals for the preference page message (see also https://github.com/eclipse-platform/eclipse.platform.ui/pull/810):

1) `Show not more than given number of children per parent in views:`
2) `Limit displayed children per parent in views:`
3) `Limit displayed elements in views with increment:`
4) `Default increment for displaying elements in UI:` (current state)
5) `Maximum number of elements shown in views:`

The last proposal has following problem: It is not correct, because views will be not limited to the given number of elements as message suggests.

What about: 
6. `Initial maximum number of elements shown in views:` 
7. `Default initial maximum number of elements shown in views:` 
8. `Initially limit number of elements shown in views:` ?

Tooltip: `Use 0 for no limit. If the number of elements exceeds given limit, user interaction is required to show more elements. This limit is a hint: not all views support support this limit or may use different one.`

**Comment by iloveeclipse** [comment]
@jukzi, @raghucssit (and anyone else interested) : any opinion on proposals 6. - 8. above?

**Comment by jukzi** [comment]
6 is fine

**Comment by jukzi** [comment]
> Tooltip: `Use 0 for no limit. If the number of elements exceeds given limit, user interaction is required to show more elements. This limit is a hint: not all views support support this limit or may use different one.`

one "support" too much

Tooltip: `Use 0 for no limit. If the number of elements exceeds given limit, user interaction is required to show more elements. This limit is a hint: not all views support this limit or may use different one.`
