### ISSUE TITLE
 SoftLimit: Improve message shown for expandable node

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.ui#1028]
I noticed that in  a scereenshot of @jukzi rported issues:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/f67156d7-4f6f-4eff-b4ac-acc38f5cd19a)

It currently says:

`Show 21..30 (91)`

but from looking at this as a user I find this not very informative, e.g. does it mean that there are 91 *total* items? Does it mean there are 91 item to *expand* or will there be 91 times an expansion showed up?

**Comment by jukzi** [comment]
suggestion for text: "<13.124 more items>" and a tooltip that verbose explains additional numbers (if anybody needs those)

**Comment by iloveeclipse** [comment]
> <13.124 more items>

This doesn't suggest user that one can do something with that. Also assuming user understood that it can be clicked, it doesn't say it will NOT show all the remaining 13.124 items, but just a subset of it.

"Show ..." invites for an action.

What about "Show next N items from X remaining"?
So above it would say "Show next 10 items from 91 remaining"?

**Comment by jukzi** [comment]
> This doesn't suggest user that one can do something with that

It may need some tries to find an intuitive well looking approach. Using [links](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1025#issuecomment-1680174608) it could be something like

`"(<link>X</link> more items ) <link>next N</link>"`

I would skip imperative words like "Show" because that is yet an unused pattern, while a hyperlink suggests an Action.
Also i would favor if the action to expand is not triggered by the text but when clicking on an ">" symbol to be add in front. because thats the existing pattern in our explorers.

**Comment by mickaelistria** [comment]
I agree the current label may not be easy to understand for non-developer. More prose would make it more accessible to all.

> So above it would say "Show next 10 items from 91 remaining"?

That sounds good.

**Comment by mickaelistria** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1041 would make this issue less critical, or even irrelevant.
