### ISSUE TITLE
Multiselection: "Select All" not working on read only Console

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1029]
Using the find/Replace dialog in a console View the action "Select All" does only show "String not found"
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/bd5b46ba-0bed-4f6e-914f-c051c685937f)

BTW: i was trying to count events with that

**Comment by HeikoKlare** [comment]
Just experienced that same issue yesterday.
The reason is that the "select all" functionality checks wheter the target is editable:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/e8fbf41dc1ebd732f6a05b4933204d7f858f1574/bundles/org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/texteditor/FindReplaceDialog.java#L1604-L1608

https://github.com/eclipse-platform/eclipse.platform.ui/blob/e8fbf41dc1ebd732f6a05b4933204d7f858f1574/bundles/org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/texteditor/FindReplaceDialog.java#L1466-L1477

This originates from `selectAll` being a "cleaned-up" copy of `replaceAll` (see the method comment and variable names).

I will provide a PR that fixes this if no one else already started working on the issue

**Comment by jukzi** [comment]
> The reason is that the "select all" functionality checks wheter the target is editable:

Explains why it works in editable Stack Trace Console. Thanks for working o it!
