### ISSUE TITLE
Add new LocalResourceManager(parent) constructor

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#1208]
I (always I think) use new LocalResourceManager(JFaceResources.getResources(), parent). If that is a common patter for others too, I suggest we should add new LocalResourceManager(parent) returning new LocalResourceManager(JFaceResources.getResources(), parent);

@HannesWell WDYT?

**Comment by laeubi** [comment]
What about having this not on `LocalResourceManager` but instead of

`JFaceResources.for(Control control);`

I think its fair to assume the `JFaceResources.getResources()` as parent, and it is much more readable / obvious and one can even have this cached for multiple calls in the Controls data section.

**Comment by vogella** [comment]
Sounds nice @laeubi , I plan to provide a PR for this.

**Comment by vogella** [comment]
for is keyword, so I suggest to use managerFor

**Comment by HannesWell** [comment]
> What about having this not on `LocalResourceManager` but instead of
> 
> `JFaceResources.for(Control control);`

Sounds good.

> for is keyword, so I suggest to use managerFor

I also wanted to suggest `JFaceResources.managerFor(Control control)` to make the name more clear. :)

**Comment by laeubi** [comment]
> for is keyword, so I suggest to use managerFor

Java seems to use "of" (e.g. `Path.of(...)`) but I' have no strong opinion about the name...
