### ISSUE TITLE
[Find/Replace] deactivating Find/Replace-Dialog deselects the entire text-selection

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#1235]
## description
When I search only in a selection of code and leave the Find/Replace-Dialog, the selection is deselected, no matter where I click

## reproduce
1) select code in editor
2) Ctrl+F
3) Setup Find/Replace-Dialog `[x] Selected lines`
4) press the window key (or do anything else that loses focus on the Find/Replace-Dialog
5) See the selection from 1) being unselected

## Expected behaviour
I expect the selection of code to stay selected until a new selection of code is performed in the editor. In particular, when text is selected but not used as search-scope, you can select another window or presss the window key without losing your selection.

I can tackle this bug in #1132

**Comment by Wittmaxi** [comment]
The same behaviour happens when you exit out of the Dialog with a selection still active. IMHO, the Dialog should give the selection back to the user after leaving the Dialog

**Comment by fedejeanne** [comment]
The selection also goes away if you do something else that keeps the selection on the Find/Replace-Dialog (contrary to what point number 4 says), like simply typing something into the _Find:_ test field. BTW, the search doesn't happen inside the selection _i.e._ it ends up finding stuff that are **outside** the selection

**Comment by HeikoKlare** [comment]
I am not sure whether the original issue is still relevant and/or even reflects expected behavior. The opinion might have changed in the last months.

> The selection also goes away if you do something else that keeps the selection on the Find/Replace-Dialog (contrary to what point number 4 says), like simply typing something into the _Find:_ test field. BTW, the search doesn't happen inside the selection _i.e._ it ends up finding stuff that are **outside** the selection

I cannot reproduce that. In my current setup (I20240410-1800), working _within_ the dialog does not result in the selection being lost.

What I experience is that when starting the dialog with having multiple lines selected, the "selected lines" option is activated but no lines are selected. That is definitely a regression from one of the latest changes and needs to be investigated, @Wittmaxi.
So to reproduce:
1. Have a selection across multiple lines
2. Press CTRL + F to open the dialog

You will result in a dialog with "selected lines" activated by no lines marked in the editor (and the search will not be restricted to that region).

This is how it looks like:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/4dfc74ee-15f2-43af-9b34-33e1b112da97)

And this is what it needs to look like:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/8b91fe4a-4fbc-4e93-995e-4c3a6c4c0a06)

**Comment by fedejeanne** [comment]
> > The selection also goes away if you do something else that keeps the selection on the Find/Replace-Dialog (contrary to what point number 4 says), like simply typing something into the _Find:_ test field. BTW, the search doesn't happen inside the selection _i.e._ it ends up finding stuff that are **outside** the selection
> 
> I cannot reproduce that. In my current setup (I20240410-1800), working _within_ the dialog does not result in the selection being lost.

Sorry, I just noticed the problem happens when one triggers the search and **not** when one merely writes in the _Find:_ text field. It just so happens that I had the _Incremental_ option checked and writing in the _Find:_ field triggered the search. I just reproduced the problem in ` I20240411-1800`. 

To recap:
### How to reproduce
1. Select code
2.  Open the Find/Replace dialog (`Ctrl + f` in windows) --> The code remains selected (good)
3. Enter something in the _Find:_ text field and press the _Find_ button (or `Enter`). 

Alternatively:
3. Select the _Incremental_ option
4. Enter something in the _Find:_ text field 

### Behavior
* The selection in the editor goes away and the search is performed in **all the lines** (bad)
* The _Find/Replace_ dialog still has the option "Selected lines" activated (bad)


### Reproduced in
Version: 2024-06 (4.32)
Build id: I20240411-1800
OS: Windows 10

I think this issue is the same as (or at least very similar to) #1454 , especially [this reported behavior](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1454#issuecomment-1978534054). It seems to me like loosing the selection is the root of all problems.

**Comment by fedejeanne** [comment]
BTW loosing the selection [like this](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1454#issuecomment-1978534054) was also possible in 4.31, I just download it and checked it.

**Comment by HeikoKlare** [comment]
> Sorry, I just noticed the problem happens when one triggers the search and **not** when one merely writes in the _Find:_ text field.

I cannot reproduce that either. Having a proper selected area and starting a search, changing the find string, either with incremental mode or not, all results in proper search within the selected area.

What you describe as a reproducer relies on the bug that I have explained in my previous post: when opening the dialog with multiple lines selected, the "selected lines" option is activated but no lines are selected (as you can see by the highlighting of the lines).

**Comment by fedejeanne** [comment]
> What you describe as a reproducer relies on the bug that I have explained in my previous post: when opening the dialog with multiple lines selected, the "selected lines" option is activated but no lines are selected (as you can see by the highlighting of the lines).

... fine but subtle difference, good catch :-)

You're right, the initial state is all wrong since the lines are not really selected. Switching back and forth between "All" and "Selected Lines" **once** solves the problem and switching twice introduces [this error](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1454#issuecomment-1978534054).

In the hope to reduce further confusion, here's a short video:

![Search selected lines bug in Eclipse](https://github.com/eclipse-platform/eclipse.platform.ui/assets/2205684/4412d207-16a3-4958-88fa-718ecb58f9bb)

**Comment by HeikoKlare** [comment]
> You're right, the initial state is all wrong since the lines are not really selected. Switching back and forth between "All" and "Selected Lines" **once** solves the problem and switching twice introduces [this error](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1454#issuecomment-1978534054).

To avoid further confusion: there has only been _a single_ real issue reported so far, which is the missing selection of lines when opening the dialog, as explained in https://github.com/eclipse-platform/eclipse.platform.ui/issues/1235#issuecomment-2051244008. The other problems relate to this as a root cause.

In particular, #1454 is a completely different topic and is also not an error but simply existing behavior (which has been there probably forever). The only question is whether intended behavior should be changed here, but actually the existing behavior can also constitute valid intended behavior.

**Comment by fedejeanne** [comment]
> To avoid further confusion: there has only been _a single_ real issue reported so far...

Would you (@HeikoKlare) or @Wittmaxi kindly provide a short video displaying the error? I still find it difficult to understand. I created my videos with [ScreenToGif](https://github.com/NickeManarin/ScreenToGif).

**Comment by Wittmaxi** [comment]
@HeikoKlare @fedejeanne yes, this is a bug. It is intended that the Dialog sets the selection for the Area-Search. It partially does that (hence the selected radio-button) but fails to propagate this search option to the Find/Replace-Logic.

**Comment by Wittmaxi** [comment]
Also I would say that this particular issue here is closed. This behavior somehow makes sense and "restoring" the selection would also be confusing (for example, when you have already selected something, ...)

**Comment by HeikoKlare** [comment]
Closing this issues as it is not an issue (anymore). Discussion on independent issue discussed in this thread to proceed in separate issue: #1819
