### ISSUE TITLE
Add preferred way of logging to ILog

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#1263]
Currently we offer multiple ways to get access to log a message:

```
public static ILog of(Class<?> clazz)
public static ILog of(Bundle bundle) 
public static ILog get() 
```

As a consumer get() is the shortest, hence I would prefer this one. But I don't know if STACK_WALKER is an expensive operation.

@HannesWell which logging method is our recommended approach? I can add this to the Javadoc for these methods in case you do not have time for this.

**Comment by vogella** [comment]
As least PDE only uses ILog get() in two places

**Comment by HannesWell** [comment]
> As a consumer get() is the shortest, hence I would prefer this one. But I don't know if STACK_WALKER is an expensive operation.

That's right, `ILog.get()` is the most convenient way to get a log and is also guarded against copy-past errors.
Of course `ILog.of(Class)` is faster, since the class does not have to be determined using the StackWalker and if one already has a Bundle at hand  `ILog.of(Bundle)` is even faster since it does not try to obtain the bundle from the file (which also could theoretically fail, but I haven't seen that in a real scenario yet).

But the performance here is all relative. I have never measured any of these, but situations where one wants to log something are usually not the most performance critical ones (e.g. log an error that happened before aborting) so I wouldn't be concerned too much or at least do some measurements before optimizing.
If you have done some measurements about the StackWalker perfmence I would though be interested in the results.

**Comment by vogella** [comment]
OK, so no need to add something to the Javadoc, all are OK to use, unless we find at a later point a performance bottleneck. Thanks for the clarification @HannesWell
