### ISSUE TITLE
Filter in Quick Access similar to VsCode

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#127]
In VsCode you can filter based on the category, e.g. Git: as in the following screenshot.

![image](https://user-images.githubusercontent.com/139910/173109654-e3c10d5a-4826-4ff7-b5b7-850582e840ba.png)

Would be super useful to have this also in Eclipse, e.g. for New: or View:

**Comment by vogella** [comment]
Adding a few people which showed interest into usability of Eclipse cc @jukzi @mickaelistria @marcushoepfner

**Comment by Bananeweizen** [comment]
If you just want to filter for the different kinds of quick assist entries (as indicated by your "New: or View:" example), that already works, without the colon (e.g. type "view" and you get all views, but the number is still limited, so you have to use ctrl-3 again to see all).
Coming back to your original request, wouldn't it be easier to just add the category of commands to the text that is being matched, instead of inventing a different kind of query? That way just typing "git" would find any git command, independent of whether it has "git" in the label/title.

**Comment by vogella** [comment]
> If you just want to filter for the different kinds of quick assist entries (as indicated by your "New: or View:" example), that already works, without the colon (e.g. type "view" and you get all views, but the number is still limited, so you have to use ctrl-3 again to see all). Coming back to your original request, wouldn't it be easier to just add the category of commands to the text that is being matched, instead of inventing a different kind of query? That way just typing "git" would find any git command, independent of whether it has "git" in the label/title.

It is great to add additional elements but it would also be nice to be filter elements based on categories, I don't think this works at the moment:

![image](https://user-images.githubusercontent.com/139910/174253522-487b02e5-82cc-4c2e-801f-4a35ffd9f058.png)

**Comment by Bananeweizen** [comment]
Yes, you still get the matches of the other categories, that's right. AFAIK there is currently no way to suppress matches, you will always get all matches.

**Comment by akurtakov** [comment]
Is this one finished?

**Comment by mickaelistria** [comment]
> Would be super useful to have this also in Eclipse, e.g. for New: or View:

Do you have an example of 1 action or command user is currently having hard time to find and that would be more efficiently found with the proposed filters.
