### ISSUE TITLE
Remove or disable Workspace version check dialog

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#149]
We currently show a warning dialog if a workspace is opened with a newer or older version of Eclipse? What is the value and what do we expect the user to do?

AFAIK we recommend reusing workspaces with newer Eclipse versions. If that is the case we should remove or disable the version check by default. 

cc @akurtakov @marcushoepfner @sratz WDYT?

**Comment by merks** [comment]
I thought the value was to make the user aware that such a workspace may no longer work with an older IDE and that if they want it to continue working with an older IDE they shouldn't use it with the newer IDE.   What's the exact text of the message?

**Comment by trancexpress** [comment]
No thanks, I prefer to be told explicitly that I might be breaking a workspace by using it. Same for users of the product I work on.

-1 from me

**Comment by dstango** [comment]
Would it be reasonable to have a (semantic) version number of the workspace configuration files instead of the eclipse version that would allow to actually tell if breaking changes are to be expected?

**Comment by vogella** [comment]
@dstango that would be nice, with this we would have a reasonal warning and not not a random dialog. AFAIK we have not changed workspace configuration structure in > 10 years.

I currently do know how to get the information about the workspace version. Anyone knows that?

**Comment by vogella** [comment]
> I thought the value was to make the user aware that such a workspace may no longer work with an older IDE and that if they want it to continue working with an older IDE they shouldn't use it with the newer IDE. What's the exact text of the message?

![image](https://user-images.githubusercontent.com/139910/174250754-ad04a55a-5ce6-4320-bc0b-c53cbf2e171a.png)

**Comment by laeubi** [comment]
@vogella it is not really only the workspace *format* but in most cases a newer eclipse also has newer *plugins* and they might write data there that older versions can not read anymore and thus you *might* be break your path to go "backward"... anyways for those not like the message, as your screenshot shows, there is a "do not warn again"....

**Comment by merks** [comment]
Note that any plugin that stores metadata in the workspace could store it in a form not recognized by an older version of that plugin, so I don't think there is a semantic version that can be maintained by the platform itself...

**Comment by vogella** [comment]
Ok, lets close this issue.

**Comment by trancexpress** [comment]
A quick search on my personal bugs for ```workbench.xmi``` shows:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=574805
https://bugs.eclipse.org/bugs/show_bug.cgi?id=527934
https://bugs.eclipse.org/bugs/show_bug.cgi?id=574819

There are definitely changes being done, that break (to some degree) even re-using the same workspace with a newer Eclipse.

You can argue "well the user will still use the new workspace anyway, lets hide the dialog because most of the time its not an accurate warning". But the dialog must stay if you try to open a newer workspace with an older Eclipse. Who knows what is broken in which ways in that scenario.

The value of the dialog is that you can abort the start-up if you e.g. made a mistake and don't want / can't risk to ruin your workspace. Once Eclipse is up its too late.
