### ISSUE TITLE
Too many open Editors - can't read name

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1570]
open all files in org.eclipse.jdt.internal.compiler.ast
this is how it used to look:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/0f1dc09e-2c6c-401a-9556-12f6f5af43fb)

this is how it looks now:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/f73c5b86-1dd4-490b-96fd-4b3210c9f799)

**Comment by jukzi** [comment]
eclipse.buildId=4.31.0.I20240124-1800
java.version=21.0.2

**Comment by HeikoKlare** [comment]
fyi: maybe #1071 is the reason, as also reported in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1071#issuecomment-1887786168

**Comment by jukzi** [comment]
i also get a lot of exceptions in the log while doing it:
don't know if its related
```
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.AbstractDocument.addPosition(AbstractDocument.java:341)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.addPosition(SynchronizableDocument.java:212)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightingPresenter.updatePresentation(SemanticHighlightingPresenter.java:214)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightingPresenter.lambda$0(SemanticHighlightingPresenter.java:149)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4046)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3662)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.views.log.EventDetailsDialog.open(EventDetailsDialog.java:198)
	at org.eclipse.ui.internal.views.log.EventDetailsDialogAction.run(EventDetailsDialogAction.java:102)
	at org.eclipse.ui.internal.views.log.LogView.lambda$2(LogView.java:599)
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:779)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:776)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1542)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1205)
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:271)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:328)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4273)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4071)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

```
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/a6e27e26-d3f4-4003-81cb-30726ab865d6)

**Comment by jukzi** [comment]
> fyi: maybe #1071 is the reason, as also reported in [#1071 (comment)](https://github.com/eclipse-platform/eclipse.platform.ui/pull/1071#issuecomment-1887786168)

@marcushoepfner @praveen-skp please check

**Comment by merks** [comment]
@MohananRahul @akurtakov 

I hope the Platform's SimRel m2 will **not** be like this!

**Comment by jukzi** [comment]
the BadLocationException seems unrelated, i also can reproduce it in 2023-12

**Comment by iloveeclipse** [comment]
> this is how it looks now:

:scream:

**Comment by laeubi** [comment]
> the BadLocationException seems unrelated, i also can reproduce it in 2023-12

I also get this regulay together with:
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1807

it makes working with Java quite hard, sometimes its all wrecked and I need to restart my IDE to even get save working in the Java editor again...

**Comment by HeikoKlare** [comment]
@jukzi are you able to reproduce the behavior of editor tab titles reduced to one character in an Eclipse application started from within an Eclipse IDE? I always have the old, proper behavior there and only face the changed behavior in my "main" Eclipse IDE. Both are based on the current state, i.e., an Eclipse application is started from up-to-date sources and TP, and main Eclipse IDE uses artifacts from Wednesday's I-Build.

**Comment by HeikoKlare** [comment]
Small addition: it seems like somehow no editor area is present in our  IDEs (anymore). You can see that when you have no document open (e.g. in the Java perspective), the onboarding information is not shown:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/e8ce515b-fe04-42eb-aee4-353f13e8c255)

Since the documents are opened in a view area (which always had a minimum character size of 1 for the tabs), the behavior seems to be "correct", except that there should be an editor area.
When I start an Eclipse application out of the IDE, the editor area is present and tabs are "properly" shown.

**Comment by HeikoKlare** [comment]
Looks like some configuration for the workbench window  (e.g. in the `workbench.xmi`) broke when updating the IDE. When you do a clean setup (via Oomph), everything is as expected. You can easily fix this by just opening a new workbench window and closing the old one.

> I hope the Platform's SimRel m2 will **not** be like this!

Luckily, this does not seem to be the case.

**Comment by jukzi** [comment]
> @jukzi are you able to reproduce the behavior of editor tab titles reduced to one character in an Eclipse application started from within an Eclipse IDE?

no. i only see the defect in the binary.

**Comment by jukzi** [comment]
> Looks like some configuration for the workbench window (e.g. in the `workbench.xmi`) broke when updating the IDE. When you do a clean setup (via Oomph), everything is as expected. You can easily fix this by just opening a new workbench window and closing the old one.

The question is then what broke it and what will happen if anybody updates it's IDE with M2... will it break their workspace too? It's not enough to find a workaround to fix it if the workaround will be needed by almost everyone

**Comment by HeikoKlare** [comment]
> The question is then what broke it and what will happen if anybody updates it's IDE with M2... will it break their workspace too? It's not enough to find a workaround to fix it if the workaround will be needed by almost everyone

Sure, but I am not able to do that anymore as I lost my faulty state by finding the "workaround". And all my other IDEs setups seem to be fine. Can you please share your workbench.xmi of the broken IDE? Maybe we can find something in there.

**Comment by merks** [comment]
I think this got into this state just Oomphing the SDK setup from scratch on January 20th.  I rename the file extension to be able to drop it:

[workbench.txt](https://github.com/eclipse-platform/eclipse.platform.ui/files/14064520/workbench.txt)

**Comment by jukzi** [comment]
[workbench.zip](https://github.com/eclipse-platform/eclipse.platform.ui/files/14064532/workbench.zip)

**Comment by merks** [comment]
I can confirm that unzipping an SDK from the most recent I-Build with a fresh workspace does not manifest the problem.

**Comment by merks** [comment]
A freshly Oomphed SDK also does not manifest the problem.

**Comment by HeikoKlare** [comment]
Thank you both for provinding the workbench.xmi and thanks for confirming that new setups do not have that problem, Ed!

I have tried with your workbench.xmis and they reproduce the problem, so it is manifested somewhere in that xmi. I have tried to reduce it to a simple version and compare it with a properly working one, but did not find yet what property causes the problem. Maybe I can spend some further time to find it this afternoon.

**Comment by laeubi** [comment]
@HeikoKlare you probably want to look for the `org.eclipse.e4.primaryDataStack` and references as this should be "the editor area" for eclipse.

**Comment by HeikoKlare** [comment]
> you probably want to look for the `org.eclipse.e4.primaryDataStack` and references as this should be "the editor area" for eclipse.

Thank you, @laeubi! That was a great help.

Usual workbench.xmis contain an entry like this for the shared area:
```xml
<sharedElements xsi:type="advanced:Area" xmi:id="_bHmz0LxDEe6VlZTMrUoCsQ" elementId="org.eclipse.ui.editorss">
  <children xsi:type="basic:PartStack" xmi:id="_bHmz0bxDEe6VlZTMrUoCsQ" elementId="org.eclipse.e4.primaryDataStack">
    <tags>org.eclipse.e4.primaryDataStack</tags>
    <tags>EditorStack</tags>
  </children>
</sharedElements>
```

Such an entry is missing in the "broken" xmis, or, more precisely, the according area entry contains a reference to a part stack whose id does not exist in the xmi, like:
```xml
<sharedElements xsi:type="advanced:Area" xmi:id="_ESRH0LE_Ee6CSp5WgbUKJA" elementId="org.eclipse.ui.editorss" selectedElement="_AMAdMLuMEe6h0tprd-b7rg">
  <children xsi:type="basic:PartStack" xmi:id="_AMAdMLuMEe6h0tprd-b7rg" elementId="PartStack@23ad2d17"/>
</sharedElements>
```
Replacing this entry with the upper one fixes the issue.

But I have to admit that I still have no real clue why some update broke the configuration. I have taken a look at recent changes to code related to the shared area, but the only ones I found are #1461 and #1462 and I do not see any reason why they should produce this behavior.

**Comment by laeubi** [comment]
@HeikoKlare I now encountered the same problem, I tried to use "Reset Perspective" but this seem not to help.

Regardless of editor area or not I find it a bit uncomfortable to have things shrink that small at all, this does not seems useful at all it even goes to the extreme that only the closing [x] is shown for a tab meaning I can not select a tab at all but only close it unless I'm very very careful finding the last pixels that not belong to the close button:

![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/4b0d3bba-eaab-4112-ab50-6c9ae685a3d7)

**Comment by merks** [comment]
Use Window -> New Window.  Close the old Window.  I think key shortcuts don't work in new window, so then a restart and all should be better.

**Comment by jukzi** [comment]
is it possible that the  workbench.xmi error exits for a longer period, but only became apparent due to the narrower representation?

**Comment by HeikoKlare** [comment]
> is it possible that the workbench.xmi error exits for a longer period, but only became apparent due to the narrower representation?

I don't think so. There is no narrower representation at all. This has always been the behavior for part stacks, except for the one of the shared area.

**Comment by jukzi** [comment]
> Replacing this entry with the upper one fixes the issue.

@HeikoKlare any hint to the sourcecode where those `xmi:id="_bHmz0LxDEe6VlZTMrUoCsQ"` IDs are calculated, written and read?

**Comment by HeikoKlare** [comment]
If I am not mistaken, XMI IDs are only valid for one persistence and generated when writing the XMI file. At least that should be the default behavior for saving Ecore resources. So I would look for the according logic of ID generation, read and write in the Ecore `ResourceImpl`. But I am not sure whether the E4 model does anything differently here.
It is also unclear whether this a problem in persistence (i.e., the referenced element existing in the model but not being persisted in the XMI) or whether it is already a problem of the model (i.e., there is some reference to an element that is not contained in the model). I would expect the latter, but that's only a guess.
I expect the reasons for this to be hard to identify unless we either have a reproduction scenario or a state of the code that first produces the behavior (such that we can have a look at potentially causing commits).

**Comment by merks** [comment]
XMI IDs are generally UUIDs that are generated when the element is saved the first time and should remain associated with that element as long as the element continues to exist.  It's generally reused even if the element is moved from one resource to another.  It's managed by this:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/c74f91dc-5203-4d1f-8b10-a1f83ead3529)

I thought the problem was the missing tag:
```
<tags>EditorStack</tags>
```

**Comment by HeikoKlare** [comment]
Thank for clarification, Ed! Then I mixed this up with the behavior of the UML2 metamodel, whose resource implementation created new XMI IDs on every save operation. And yes, the problem does not even seem to be related to XMI IDs.

> I thought the problem was the missing tag:
> 
> ```
> <tags>EditorStack</tags>
> ```

That tag is missing because the complete part stack seems to be missing. There is no part stack (for the shared area) in the XMI but only a reference in the element id (`elementId="PartStack@23ad2d17"`). But that referenced element does not exist. So probably when persisting the XMI, this part stack was not contained in the according model. Maybe it was contained in some other model or it was just referenced without being contained in any model (should then persisting fail with some validation error?).

**Comment by merks** [comment]
I'm a bit concerned about this issue because I created a brand new SDK workspace February 16th and now it too has this problem:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/4d2fc67c-2800-4b96-8a37-06a72645b0e3)

So I get a bad feeling about that...

A dangling reference (a reference to an object one not contained in a resource) is handled by this:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/e00ce841-4742-4f23-af17-58fb07467bf9)

That exception will be thrown at the end:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/46123157-c958-447f-8f1b-969be1ffac57)

At least unless configured otherwise.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/4482a898-8c63-419b-b048-9a5a8c5a5a1e)

I see nothing that changes this default behavior.

**Comment by HeikoKlare** [comment]
> I'm a bit concerned about this issue because I created a brand new SDK workspace February 16th and now it too has this problem:

That's really bad news 🙁 Do you remember anything special you did with that workspace before the issue occurred? In particular, before you last restarted the IDE, because that's when the faulty workbench.xmi must have been created. Would be really great if we found a way to reproduce the behavior.

We should try to avoid shipping 2024-03 release with that bug. I will take a look at the code that produces the XMI to understand how such a broken XMI can be produced.

Otherwise, we could at least take a look at what happens when that broken XMI file is read. Maybe we could introduce some kind of fallback when such a broken entry exists to then restore the shared area part stack. That's obviously not a proper solution, but in case we do not find the cause soon, it may be better than accepting the current behavior.

**Comment by merks** [comment]
I will try tomorrow to see if I can reproduce this problem somehow...

**Comment by BeckerWdf** [comment]
@merks @HeikoKlare : Can you pls. have a look at the draft PR https://github.com/eclipse-platform/eclipse.platform.ui/pull/1712.
@praveen-skp has issues that injecting EModelService does not work. Can you help here?

**Comment by merks** [comment]
For completeness, this is a copy of the content in the above PR describing how to reproduce the problem:

---

When trying to reproduce the cause of the problem I already notice this problem, i.e., if you drag an editor to create a split editor area, the second area's tabs are squished:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/28571f13-b4c7-425b-97a4-ff7410ed28ed)

If you now close all the editors and open new editors, those tabs are squished as well:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/45de2186-097e-4320-ba0c-6defb920930f)

So it's highly likely that anyone who ever create such a split editor area will always see this problem and will them permanently see this problem...

**Comment by BeckerWdf** [comment]
I have the impression that the issue with the disappearing tag already exists longer (did somebody test with the previous release?) and that the changes to the tab rendering "only" make it visible. Do you agree?

**Comment by merks** [comment]
Yes, I have the impression this has existed for a long time and is only obvious now because of rendering that 100% relies on the tag.  In general it's not even clear if more than one area should have the tag, what else is the purpose of the tag, what else doesn't work when the tag is missing, and so on...

**Comment by HeikoKlare** [comment]
Thanks, Ed! That actually seems to be the root cause of the problem. It is even reproducible with older Eclipse releases. I tested with Eclipse 2023-06 and the same behavior (editor area being lost) occurs. It does not have the effect of small tab headers in that release, but you can see the onboarding area disappearing (which was introduced with 2023-06 IIRC) and of course by looking at the workbench.xmi.

After starting new IDE:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/159d7d73-7991-40b8-a236-cfb89bbaa5d8)

After splitting editor area and closing the remaining tabs of the original editor area:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/1414e951-768c-471e-85ed-494f0ac35746)

It does not make sense to try to fix the root cause for 2024-03 since it would be too risk to merge anyway, right? So for now focussing on fixing the tab headers (like addressed in #1712) is sufficient?

**Comment by merks** [comment]
We don’t know the risks without knowing what needs to change.  But the change for the rendering logic is only that some tabs might not be so squishy which is way less horrible than unreadable editor tabs.

**Comment by HeikoKlare** [comment]
> We don’t know the risks without knowing what needs to change. But the change for the rendering logic is only that some tabs might not be so squishy which is way less horrible than unreadable editor tabs.

Sure. I can have a look at how to fix the root cause, but unfortunately I am quite busy the next days, so if anyone wants to work on that meanwhile, feel free. The problem seems to be that a part stack is removed once the last part in that stack is closed. This is the case even if the editor is a shared/editor area. My expectation would be that the shared editor, when activated, can _never_ be closed. So in the problematic scenario (splitting the editor area and closing the last tab in the original area), I see options: 
1. The split area is collapsed to a shared area, such that even if the last tab in the original shared area is closed, that area remains and all tabs from the other area are moved to this area.
2. The area remains in split state with the shared area then being empty (and showing the onboarding information again). Currently, it is simply removed.

The second option could look as follows. When starting with this:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/aaba412e-06d2-4591-a0db-583d32925d1f)

... I would expect this:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/21087686-ad7b-41a1-88c7-0271927bfa5e)

... while currently it is this:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/e7427da3-5e25-4b00-9758-df5b98150ff1)

If anyone knows where the according code that removes a part stack once the last part is closed is located, it might be an easy fix.

**Comment by BeckerWdf** [comment]
> We don’t know the risks without knowing what needs to change. But the change for the rendering logic is only that some tabs might not be so squishy which is way less horrible than unreadable editor tabs.

I just updated the PR with @merks proposal.
Feel free to approve and merge once CI is green.

**Comment by BeckerWdf** [comment]
> If anyone knows where the according code that removes a part stack once the last part is closed is located, it might be an easy fix.

Maybe @vogella knows this.

**Comment by HeikoKlare** [comment]
Here are some further insights, which I want to share for those interested in the information or interested in working on the bug, as I will not proceed with this for the next days.

## Current Behavior

Whenever you split the shared area, so that it contains multiple part stacks, and then close the last editor in the original part stack (which is the "primaryDataStack"), the "primaryDataStack" will be lost.

The code that removes a part stack is this, precisely the call `ensureComposite(areaModel, stacks)`:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/e6309193420f45895654d404d9f2adf875ca9432/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/AreaRenderer.java#L218-L231

When you close the last editor in the primary data stack, that part stack will simply be removed. Then no part stack being the primary and potentially also no part stack being tagged as `EditorStack` remains.

Interestingly, the part stacks with element id `PartStack@XXX` are no dangling references, That's just the result of some fallback code to ensure that every part stack has an element id:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/e6309193420f45895654d404d9f2adf875ca9432/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/StackRenderer.java#L701-L704

## Expected Behavior

I would expect the following behavior:
- When I instantiate a new part stack within the shared area (usually via drag&drop), it should also be marked as "EditorStack".
- When the part stack being the "primaryDataStack" is closed (which can only happen if the there are other part stacks in the shared area), the first remaining part should become the new "primaryDataStack".

The creation of a new part stack by splitting an area via drag & drop is handled in `SplitDropAgend2#drop()`:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/e6309193420f45895654d404d9f2adf875ca9432/bundles/org.eclipse.e4.ui.workbench.addons.swt/src/org/eclipse/e4/ui/workbench/addons/dndaddon/SplitDropAgent2.java#L293-L298
You can see that this new part stack will never be tagged as "EditorStack". When such a part stack becomes the last remaining in the shared area, without any editor open, the onboarding information is not shown as this depends on presence of exactly that tag:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/e6309193420f45895654d404d9f2adf875ca9432/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/StackRenderer.java#L709-L711

## Preliminary Solution

With the following adaptation of `AreaRenderer#synchCTFState()`, the current removal of the primary data stack can be avoided by passing it to the first remaining part stack. However, this is not a clean solution yet, which is why I do not propose it in a PR:
```java
	private void synchCTFState(MArea areaModel) {
		final String primaryDataStackId = "org.eclipse.e4.primaryDataStack"; //$NON-NLS-1$
		List<MPartStack> stacks = findDirectStacks(areaModel);
		List<MPartStack> visibleStacks = new ArrayList<>();
		boolean removingPrimaryDataStack = false;
		for (MPartStack stack : stacks) {
			if (stack.isToBeRendered()) {
				visibleStacks.add(stack);
			} else {
				if (primaryDataStackId.equals(stack.getElementId())) {
					removingPrimaryDataStack = true;
				}
			}
		}

		if (removingPrimaryDataStack && !visibleStacks.isEmpty()) {
			MPartStack newEditorStack = visibleStacks.get(0);
			newEditorStack.setElementId(primaryDataStackId);
			newEditorStack.getTags().add(primaryDataStackId);
			newEditorStack.getTags().add("EditorStack"); //$NON-NLS-1$
		}
		// If there's more than one stack visible we use a CTF
		if (visibleStacks.size() > 1)
			ensureCTF(areaModel, stacks);
		else {
			ensureComposite(areaModel, stacks);
		}
	}
```

**Comment by vogella** [comment]
> > If anyone knows where the according code that removes a part stack once the last part is closed is located, it might be an easy fix.
> 
> Maybe @vogella knows this.

CleanupAddon should be responsible for this. If you add a tag from the IPresentationEngine to the stack it is ignored,the tag is called IPresentationEngine.NO_AUTO_COLLAPSE

**Comment by BeckerWdf** [comment]
We have preliminary fix for this. Does anybody plan to provide PR for the "final" fix?

**Comment by merks** [comment]
My sense is that this is the correct fix for the problem (as described by the title) because it works when there are multiple areas.   It's not clear if multiple tagged areas should be created when there are multiple editor areas.  In any case, it is still a bug that the tag disappears so that we don't see the helpful "empty editor area" content:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/9dec0f10-9ae6-40bd-97fa-7a0c2bb9f70c)

I think it would be best to open a new separate issue for that specific problem;it can be linked this issue which we could revisit when that other issue is fixed.

**Comment by HeikoKlare** [comment]
> We have preliminary fix for this. Does anybody plan to provide PR for the "final" fix?

I've started to work on a "final" fix but did not find the time to finalize it yet.

> I think it would be best to open a new separate issue for that specific problem;it can be linked this issue which we could revisit when that other issue is fixed.

That makes sense. I can create that issue and open a draft PR to share my preliminary experiments, hopefully by the end of the week.

**Comment by HeikoKlare** [comment]
I have documented the remaining issue in #1773 and referenced this issue to be revisisted once #1773 has been addressed. Since the original issue in this thread has been resolved, let's proceed with further discussion in that separate issue and have this one closed, as also proposed by Ed.

**Comment by HeikoKlare** [comment]
> it can be linked this issue which we could revisit when that other issue is fixed.

I have created #1806 with some final cleanup after having introduced proper handling of the primary data stack and editor stacks in recent PRs (https://github.com/eclipse-platform/eclipse.platform.ui/pull/1775, https://github.com/eclipse-platform/eclipse.platform.ui/pull/1778). It also reverts the preliminary fix for this issue, which was only applied to avoid the bug to be visible in the 2024-03 release and which was introduced with #1712.

**Comment by merks** [comment]
So when there are multiple editor areas, none of those areas will have the shrunken tabs issue, but only one is marked as the primary stack?

**Comment by HeikoKlare** [comment]
Exactly, this is how a split-up shared area looks after this PR. Note that there are more than the displayed tabs in both stacks, but the visible ones have proper name lengths.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/ef302daa-43ec-4c1d-b2af-e1e656275b42)

**Comment by merks** [comment]
Awesome.  💯
