### ISSUE TITLE
Windows Defender exclusion cannot be added if Tamper Protection is active on the machine (e.g. InTune managed coroporate device)

### ISSUE THREAD

**Issue by sratz** [eclipse-platform/eclipse.platform.ui#1709]
The Windows Defender auto fix implemented with https://github.com/eclipse-platform/eclipse.platform.ui/pull/1453 does not work on devices where exclusion rules are tamper-protected.

The PowerShell script to add exclusions will run successfully, but the entry will not actually be added, causing the popup to re-appear next time Eclipse is started.

See https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-tamper-protection-intune?view=o365-worldwide#tamper-protection-for-antivirus-exclusions

The Windows Defender auto fix implementation should check whether exclusions are tamper-protected before showing the popup.

Microsoft describes a method to check this:

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-tamper-protection-intune?view=o365-worldwide#how-to-determine-whether-antivirus-exclusions-are-tamper-protected-on-a-windows-device

I.e., the auto fix should not be proposed when `TPExclusions` in registry key
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Features` has value `1`.

**Comment by HannesWell** [comment]
Thanks for this report and the ways to check the status.

> The PowerShell script to add exclusions will run successfully, but the entry will not actually be added, causing the popup to re-appear next time Eclipse is started.

Actually if the script execution does not fail (i.e. after you have pressed Proceed after selecting to add exclusions) nothing happens, then the pop-up should not come up again since it is just persisted that the exclusion was run for the current location.

In general, because one needs Admin privileges to run the exclusions and to check the current exclusions there is no ways to check if the exclusion was really applied. Because acquiring the privileges requires a child-shell at least I wasn't able to collect the child's output. And checking the existing exclusions would require Admin privileges again. As your college Hans-Peter summarized it: we throw the intend to apply the exclusion over the fence and hope all works well. To be sure one has to go to the Windows Settings and check the Defender exclusions manually.

So I wonder why the pop-up comes up again if the exclusion does not fail visibly?

But of course we can run the following command as initial check as well:
```
reg query "HKLM\SOFTWARE\Microsoft\Windows Defender\Features" /v TPExclusions
```
For me this returns 
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Features
    TPExclusions    REG_DWORD    0x0
```
I assume for you it returns the following?
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Features
    TPExclusions    REG_DWORD    0x1
```

**Comment by HannesWell** [comment]
It would also be interesting to now the printout if you run the exclusion script on a powershel with Admin rights on your computer.

**Comment by sratz** [comment]
> Actually if the script execution does not fail (i.e. after you have pressed Proceed after selecting to add exclusions) nothing happens, then the pop-up should not come up again since it is just persisted that the exclusion was run for the current location.
> 
> So I wonder why the pop-up comes up again if the exclusion does not fail visibly?

Sorry, my mistake, I accidentally killed the instance rather than a clean exit, so the preference wasn't persisted.



> But of course we can run the following command as initial check as well:
> 
> ```
> reg query "HKLM\SOFTWARE\Microsoft\Windows Defender\Features" /v TPExclusions
> ```
> 
> For me this returns
> 
> ```
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Features
>     TPExclusions    REG_DWORD    0x0
> ```
> 
> I assume for you it returns the following?
> 
> ```
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Features
>     TPExclusions    REG_DWORD    0x1
> ```

Yes.

Alternatively, use powershell:

```powershell
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Microsoft\Windows Defender\Features' -Name TPExclusions
```
which just returns literal `0`, `1`, making the parsing easier, (or fails, if the key doesn't exist, I guess failure here could be treated like `0`).


> It would also be interesting to now the printout if you run the exclusion script on a powershel with Admin rights on your computer.

```
PS C:\> $exclusions=@( `
>>  "C:\SAPDevelop\eclipse\dev_ide\eclipse.exe"); `
>>  $existingExclusions=[Collections.Generic.HashSet[String]](Get-MpPreference).ExclusionProcess; `
>>  $exclusionsToAdd=[Linq.Enumerable]::ToArray([Linq.Enumerable]::Where($exclusions,[Func[object,bool]]{param($ex)!$existingExclusions.Contains($ex)})); `
>>  if($exclusionsToAdd.Length -gt 0){ Add-MpPreference -ExclusionProcess $exclusionsToAdd }
PS C:\>
```

It returns no error, but the exclusions remain unmodified.

**Comment by HannesWell** [comment]
> > Actually if the script execution does not fail (i.e. after you have pressed Proceed after selecting to add exclusions) nothing happens, then the pop-up should not come up again since it is just persisted that the exclusion was run for the current location.
> > So I wonder why the pop-up comes up again if the exclusion does not fail visibly?
> 
> Sorry, my mistake, I accidentally killed the instance rather than a clean exit, so the preference wasn't persisted.

OK, so the persisting works as expected?
So the drawback of the current status is that although one selects to exclude the current installation, it is not done and one assumes it is excluded?
And you are suggesting to just not show the pop-up in that case at all since one cannot do anything?
I'm just asking to get a more clear overview of the situation.
But actually it seems to be somewhat similar to the case where one cannot get Admin Privileges (either because the current user isn't an Admin or one cannot enter the Admin passwort). In that case there is also a follow-up dialog that adding the exclusion failed.
So a third option besides leaving it as is or not showing the pop-up would be to only inform about the temper protection when one selects to run the exclusion.

> Alternatively, use powershell:
> 
> ```powershell
> Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Microsoft\Windows Defender\Features' -Name TPExclusions
> ```
> 
> which just returns literal `0`, `1`, making the parsing easier, (or fails, if the key doesn't exist, I guess failure here could be treated like `0`).

That's indeed better.

**Comment by BeckerWdf** [comment]
> So a third option besides leaving it as is or not showing the pop-up would be to only inform about the temper protection when one selects to run the exclusion.

So I think this would be best, because we give the user all the information we have.
