### ISSUE TITLE
Sticky Option for breadcrumb / additional to breadcrumb

### ISSUE THREAD

**Issue by f4abap** [eclipse-platform/eclipse.platform.ui#1719]
Originally provided it as a feature-request within the SAP-Ecospace.  
As I suggested there, this is a feature, which will provide a better usability no matter what language is used. So moved it here and hope to get that feature.

Please describe your improvement request

Provide different option for the breadcrumb / add a feature

What is the opportunity/problem the request will address?

In long statements it's difficult to see, which are dependencies, and therefore it's difficult to add the logic to the correct place. Especial when the source-code gets long

What is the expected benefit?

Will give developers a better option to navigate and see what their focus is

Found it as an option within VSCode and think this option would also be a great benefit for ABAP. Maybe it's a feature for the eclipse foundation.

Have a look here

https://devblogs.microsoft.com/visualstudio/sticky-scroll-now-in-preview/

**Comment by iloveeclipse** [comment]
I could not understand **what** exactly is the feature you request. Could you be more precise please ?

**Comment by f4abap** [comment]
As you scroll through your code, namespaces, classes, and methods will stick to the top of the editor

Here is a little example

IF 1 = 2
..imagine multiply lines of coding
else
..imagine multiply lines of coding here too
endif.

So now you scroll down to the else and then your editor will look like
IF 1 = 2
..else
somewhere in this coding section is your cursor 

Please also take your time to read through the linked blog, because there is this feature really great described.. it's just the wrong ide :-D

**Comment by Madjosz** [comment]
This is how this feature looks in Eclipse Theia:
![Sticky Scroll in Eclipse Theia](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/28844868/c8f0e230-407b-4fc3-8847-414b0d091d56)

**Comment by Christopher-Hermann** [comment]
After conducting some initial prototyping, I believe I've identified a potential solution.

In the top right corner, you can observe the 'sticky lines' displayed in an added textual area:
![StickyScrolling](https://github.com/eclipse-platform/eclipse.platform.ui/assets/79514265/7374d48c-2b08-4858-a89a-24ced99d2c32)

When the additional text is aligned so that it is displayed above the lines of the editor, I think it can be build so that it works like in the other IDEs. Of course, line numbers, navigation, etc. is missing. 

Should time permit in the upcoming weeks, I plan to look further into this feature.

**Comment by Christopher-Hermann** [comment]
First version implemented with #1894. Will be improved over time. Issue can be close in my opinion.
