### ISSUE TITLE
2024-03: "Find/Replace"-Button has no effect anymore without manually shifting focus back to the editor

### ISSUE THREAD

**Issue by reto-hoehener** [eclipse-platform/eclipse.platform.ui#1754]
To reproduce:
- Type Ctrl+F
- Click the "Replace with"-field
- Click the "Find/Replace"-button
- Nothing happens until you click into the editor again

![findreplace](https://github.com/eclipse-platform/eclipse.platform/assets/13407181/9abc2ea3-1a55-4305-a57c-621de19fbb53)

**Comment by iloveeclipse** [comment]
I can reproduce in I20240313-1800. 
The key point is to really **click** into **both** fields. If not clicking into "Find:" field, everything works.

@rhoehener : is this a regression? In which release it worked last?

**Comment by reto-hoehener** [comment]
@iloveeclipse I noticed it immediately after switching from 2023-12 yesterday, so I'm assuming it's a regression since I use this functionality a lot, but not 100% sure.

I tested again: I can reproduce this reliably by immediately clicking the "Find/Replace"-button (no need to click the Find/Replace with fields).

**Comment by iloveeclipse** [comment]
OK, seems I can't reproduce on 4.30, so must be regression in 4.31.
The most likely candidate is https://github.com/eclipse-platform/eclipse.platform.ui/pull/1132 or follow up work in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1503 and later changes.

@HeikoKlare , @Wittmaxi : could you please investigate?

**Comment by HeikoKlare** [comment]
Thanks for reporting the issue. We will have a look and provide a fix as soon as possible.

**Comment by HeikoKlare** [comment]
The reason for the bug is that replacement operations are enabled but no find operation has been executed before. An according exception is thrown and then swallowed by the dialog:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/1122c6318b76ca258867ec689e637c7efeebdca5/bundles/org.eclipse.text/src/org/eclipse/jface/text/FindReplaceDocumentAdapter.java#L150

Before #1132, some tracking for whether an initial search has to be performed before replace operations can be executed or before they should even be disabled was woven into several operations of the dialog class.

I've proposed a fix in #1765.
