### ISSUE TITLE
Resource Properties Dialog to small to see buttons

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1895]
1. package explorer
2. context menu 
3. Properties 
=>
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/c8c2e20f-8662-49dc-8ec6-60b240ffba04)
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/21eb1b85-c067-4d5f-a488-15177090c631)

```
eclipse.buildId=4.32.0.I20240516-1800
java.version=21.0.2
```
I don't remember that it used to happen in older eclipse versions (or at least **not that much** too small), so it might be a regression.

**Comment by jukzi** [comment]
That page is org.eclipse.ui.internal.ide.dialogs.ResourceInfoPage, but i could not find a related commit to that class causing the issue. May be some general change?

**Comment by HeikoKlare** [comment]
The last update of that page I am aware of was in December: https://github.com/eclipse-platform/eclipse.platform.ui/pull/1300

But from a first glance, I do not see that this change affected the general layout of that page. If I am not mistaken, I see the same behavior in an Eclipse 2020-03 IDE:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/47ed5ca6-e153-4eae-8cb6-1cbad842c28c)

In my opinion, the problem is that the text field(s) (in particular the one for the location) are sized according to their contents instead of according to the size of the container. I (personally) would prefer to scroll within the location text box rather than scrolling the whole page.

**Comment by merks** [comment]
Yes, I think it's been this way for a long time and one just doesn't notice until the location is grossly long.

One thing that has changed is this dialog remembers its bounds:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/1498bfeb-b63c-4d56-9928-fa1dcb7119a0)

So is now much more likely to come up narrow where the long location doesn't fix.

**Comment by jukzi** [comment]
This is a combination of two bugs:
1. the "Location" text is (unlike the "Path" text) not wrapped into multiple lines
2. regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/1282 @marcushoepfner that the preferred size of the page is not used anymore: The PreferenceDialog has a very custom size algorithm in org.eclipse.jface.preference.PreferenceDialog.showPage(IPreferenceNode) that tries to adapt the size of the dialog to the preferred size of the current page. That does not work anymore as for the first page always just the old size is used. Now when switching between different preference pages the size still grows a bit but not enough.
