### ISSUE TITLE
[Find/Replace Overlay] The search-history cannot be accessed from the Overlay

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#1907]
This Issue Documents a review-comment from the find/replace overlay PR
which could not be addressed into the current proposal. [comment](https://github.com/eclipse-platform/eclipse.platform.ui/pull/1192#issuecomment-1777142848) by @jukzi 

### Currently, the search-history cannot be accessed from the Overlay.
In the find/replace dialog, there is a dropdown for each the search-bar and the replace-bar, as such:
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/7db4e11c-b13c-4e2f-b835-a77af775c7fd)

### (Help wanted!) A few ideas on how to implement this into the Overlay:
-) Navigate history by pressing up/down in each Bar (VSCode does this! I am strongly in favor of this implementation!) 
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/209d95b2-2967-4297-ac52-19e9c535fbc5)
-) Add up/down buttons in the toolbar (I think this can be okay-ish)
-) Add a drop-down button to each bar (I am not keen on this idea as it would impact the flat look of the Overlay)

**Comment by jukzi** [comment]
I desperately miss this feature, especially that not even the very last search is remembered.

**Comment by HannesWell** [comment]
> -) Add a drop-down button to each bar (I am not keen on this idea as it would impact the flat look of the Overlay)

Couldn't we have drop-down arrow next to the word match button (the `Aa`) keeping the text-box in a flat-style? Having a drop-down list would have the advantage that one can see the entire available history at once instead of clicking through it one-by-one?
Visual Studio (non Code) does it like that.

Would it looks so bad to have the lines around the actual text-block? If yes, maybe SWT can be enhanced to have a flat drop-down menu for a flat text-box? Maybe just the arrow?
