### ISSUE TITLE
find/replace overlay: Cannot easily access legacy search from overlay

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.ui#1952]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace
I want to access the legacy editor which has some options I need (assistance to regex, "Select All")
I expected: (as discussed some time ago on a ticket) that the overlay would provide some button or link to switch back to "legacy" (and the other way round)
But got: overlay without convenient way to use legacy dialog

**Comment by jukzi** [comment]
On the one hand i immediately had the same desire to get the old dialog - that i am used too. On the other hand i would like to give the new dialog more time that i am get used to it and think it would be better to add the missing features instead of adding a legacy link.

**Comment by Wittmaxi** [comment]
@jukzi I agree with you!
Knowing that we still miss a search history (I will work on it next week, now that the bugs are addressed), the goal is for the overlay to be as powerful (or even more powerful than) as the search dialog.

If there is a sentiment that the old dialog is better, then we should look into why that sentiment exists and how we can improve the Overlay instead of offering a half-half solution which would end up defeating the purpose of the overlay.

**Comment by Wittmaxi** [comment]
@mickaelistria can we close this issue? If not, what can we concretely do to solve your problem? What is the (root) problem you are trying to fix with this issue?

**Comment by mickaelistria** [comment]
Let's close.
The root problem I tried to fix was some missing features that are available with search dialog (IIRC searching backwards, help/validation when writing regexp and multi-selection). I'm not using the overlay now so I cannot tell whether all those get fixed.
My general impression is that if the overlay removes some popular features compared to the legacy dialog, some people will perceive it as a regression more than as an enhancement. And the other way round: if we want overlay to be as rich as the legacy dialog, then it will be a big complex widget, which would hardly be a substantial enhancement either.

**Comment by HeikoKlare** [comment]
> My general impression is that if the overlay removes some popular features compared to the legacy dialog, some people will perceive it as a regression more than as an enhancement. And the other way round: if we want overlay to be as rich as the legacy dialog, then it will be a big complex widget, which would hardly be a substantial enhancement either.

Just as a matter of expectation management: the overlay is, of course, supposed to provide equal expressiveness compared to the existing dialog. I agree that removing existing features will be perceived as a regression. It is supposed to be a substantial enhancement in terms of usability / user experience without affecting functionality.

As a side effect, several bugs in the implementation of the find/replace functionality have been fixed while realizing the new implementation and refactoring the existing one.

**Comment by CLechleitner42** [comment]
This issue was my first hit via internet search, that's why I comment on a "closed" issue:

The "overlay" search within the editor window can by definition never do all the popup search can. For example, searching (or search+replace) in multiple open editor tabs without re-entering everything repeatedly.

To switch the overlay off: Window, Preferences, General, Editors, Text Editor, uncheck "Use find/replace overlay", Apply and Close, ...

**Comment by HeikoKlare** [comment]
> The "overlay" search within the editor window can by definition never do all the popup search can. For example, searching (or search+replace) in multiple open editor tabs without re-entering everything repeatedly.

Totally right: the overlay will indeed never provide the same functionality (in the same way) as the dialog, just the like the dialog will never provide the same functionality in the same way as the overlay. Otherwise they would be conceptually the same and so there would have been no reason for developing the new UI. It's only about the use cases one of them supports better than or in contrast to the other.

Regarding the necessity to re-enter everything for searching in multiple editors: this is an actual limitation of the overlay, but rather a limitation of the current realization and not a conceptual limitation. Of course, it is by intention that search settings are bound to an editor (which also allows you to have different settings applied to different documents in the same application, which is not possible with the dialog). But this does not need to be an either-or decision. For example, VS code has a concept for sharing search settings across multiple editors (while generally being very similiar to the overlay in Eclipse) and we also have an issue that goes in this direction:
- #2055
