### ISSUE TITLE
Input/Replace Toggle Icons Looks Strange on macOS in Dark Theme

### ISSUE THREAD

**Issue by BeckerWdf** [eclipse-platform/eclipse.platform.ui#1983]
## Steps to reproduce

* Open the find replace overlay in dark mode in macOS

I got: 
<img width="563" alt="image" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/28338612/b84810d3-d369-437f-be7a-ff204586e81b">

The background looks to light for me. The triangle is hardly visible due to bad contrast.

**Comment by BeckerWdf** [comment]
@Wittmaxi: Can you please have a look at this?

**Comment by Wittmaxi** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/pull/1916

In this PR, I changed the way I color toolbars. Crucially, I now manually color SWT.SEPARATOR-ToolItems (the one that looks odd for you). I did not do that on windows previously because it wasn't visible on windows unless I set the ToolBar to SWT.FLAT

Can you please tell me whether your issue still persists in thag PR?


Edit: Nevermind, I did not correctly read your issue. I am not sure what to do about the triangle not showing up well but it definitely is not food behavior. Maybe I could manually color the button to keep control over the theming (?)

**Comment by BeckerWdf** [comment]
> Can you please tell me whether your issue still persists in thag PR?

With #1916 this is fixed.

**Comment by HeikoKlare** [comment]
@BeckerWdf could you please verify if this issue was really fixed with #1916 for you? I still have the same light background color making the icon hardly visible on my Mac.

**Comment by BeckerWdf** [comment]
> @BeckerWdf could you please verify if this issue was really fixed with #1916 for you? I still have the same light background color making the icon hardly visible on my Mac.

You are right. The issue still exists...
