### ISSUE TITLE
Preferences should be a view

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#2050]
In VSCode, the Preferences are a view, not a (blocking) Modal.

When trying cool new things, I frequently enable/disable preferences to see which preference does what. Same thing happened, when I tried figuring out which color I need to style to change the MyLyn landmark colors (I gave up...)

VScode implements this as a singular window pane (a "view") which can be placed into the background when frequently tweaking preferences
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/9a860f36-b147-4d86-b327-62784d1d3603)

I would expect:
1) the preferences to be displayed as a view by default
2) have a preferences for the preferences being displayed as a modal (some RCPs might depend on the modal behavior (?))

**Comment by Wittmaxi** [comment]
From my naive point of view, this should be fairly easy to do: instead of rendering the components into a modal, we could just render them into a new view we create.

@mickaelistria I was told you experimented on something similar and eventually stopped. Do you have any insights or opinions on this?

**Comment by laeubi** [comment]
@Wittmaxi I don't see why not both should be possible (e.g. no specific preference/setting is required) or would it harm to keep the menu entry as is? In the same sense the view can be simply closed (like the welcome view) if anyone don't like it (and custom RCP control what views/menu items shown anyways).

Beside that, such a view will probably have some challenges, but seems something that can be solved incrementally but some are out of Eclipse control:

1. Pages need to be aware that they are "always visible" so if a preference changes programmatically or through other UI it must update itself
2. If a bundle gets updated, pages might change, but that's probably something we don't need to handle without a restart 
3. At the moment one can cancel the whole dialog, or individual pages so this must maybe be revisited how it should behave here

**Comment by humphreygao** [comment]
is it possible to rearrange the preferences in the same time? 

I think the preferences are not organized well(take Intellij for example) and are lack of explanation(please take VS Code for example, although there are help contents in Eclipse, I never use it)
And it could be archieved gradually.

**Comment by Wittmaxi** [comment]
@humphreygao I don't really see a problem with the preferences, but I am totally open to change. The thing that makes the preferences usable for me is the "search" which works really well

regardless, reordering preferences should be a new issue - I think that the most important part of this issue is to get rid of one more Dialog.
Also, more importantly, we should learn from this PR and try to find a way to quickly change all modal dialogs into views (the creation-wizard, the ctrl+h search, all other searches, ...)

"Everything that is blocking the user is old"

**Comment by vogella** [comment]
IIRC @mickaelistria started such am implementation in the past. @mickaelistria can you share details (in case I remember correctly)?

**Comment by vogella** [comment]
And of course: +2 for suggestion, most blocking dialog are bad UX IMHO

**Comment by mickaelistria** [comment]
Yes, this was tried a long time ago with Stefan Xenos and @maxandersen IIRC. At first sight, it did look promising and it seems relatively easy to reuse most of the UI in an editor (although it seems a bit heavy for an editor area, but it was working), and the tricky part IIRC was to get proper state information for save and also the fact that some pages didn't fit so comfortably in a editor area because of too many levels of scroll. Anyway, I think it wasn't too far from being good enough for general avaibility but I think it never became the top priority of anyone to continue it.
But reading the initial comment, I believe just making the preference dialog non-modal could cover your story very well with much less effort.

**Comment by vogella** [comment]
@mickaelistria I cannot find a related Gerrit / Bugzilla / PR for this work? In case you can find a link to the work, can you share it?

**Comment by Wittmaxi** [comment]
@mickaelistria that would be a good first step (which I can fairly easily do myself right now).
In the long run, I wish we could completely get rid of Dialogs (how?)

Thanks for the insight! :)

**Comment by laeubi** [comment]
> that would be a good first step (which I can fairly easily do myself right now).

Please be aware that you will have the same problems as with a view (e.g. preference page state get out of sync), also some code might rely on the fact that the user either complete or dismiss the dialog, something that JFace (as far as I know) not offering e.g. via some kind of notification concept.

So the first thing maybe would be to have an alternative `Dialog#open` that accepts an "onOK" and optionally "onCancel" handler...

Beside that, I can think of a preferencepage having a new `setDynamic` method that marks this page as usable inside such new view because it is aware of the dynamics nature (how ever it is implemented).

**Comment by mickaelistria** [comment]
> I cannot find a related Gerrit / Bugzilla / PR for this work? In case you can find a link to the work, can you share it?

I found https://bugs.eclipse.org/bugs/show_bug.cgi?id=497428 which also has a link to a PR.

> In the long run, I wish we could completely get rid of Dialogs (how?)

Good luck with that ;) I think it's a tremendous effort for average benefits and I wouldn't personally recommend anyone to invest in it because the ROI seems low and the risk seems high:
As you mentioned earlier, the interesting part of being a view/editor is more the interaction with the workbench in general. Editors/views have a lifecycle, dirty state, searchable content, react to backend document changes... that are integrated with several actions. If you try to move dialogs as editors, then those dialogs would miss such integration and then they will always feel incomplete or not fully usable until on par with editors.
A dialog allows, for better or worse, to "forget" about workbench integration and to have a standalone piece of UI that users expect to be isolated and manipulate with less expectations.

If you still want to get started on this topic, instead of preferences, I would recommend that you look at launch configurations. Those have the advantage of being backed by a File, so you can have a textual view and a dialog view, similarly to the MANIFEST.MF. Having a textual document backend makes that most workbench integrations (save, search...) would work out-of-the-box.
That's IMO a better starting point to grow knowledge and competencies about the general problem of turning dialogs to views; preferences being harder, they could be a next iteration.

**Comment by Wittmaxi** [comment]
Creating this issue has sparked some very interesting discussions internally and of course in this issue.

I now fully agree that this is not something we should do - IntelliJ and many other modern tools also have a blocking preferences dialog, they are likely also concerned with this Problem.

I will close this issue to keep the issues clean
