### ISSUE TITLE
Users of the Find/Replace dialog want to use Alt + A to perform "Search all"

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#2080]
Some users are used to pressing "Alt+A" to perform search all which was a mnemonic used in the FindReplaceDialog.
Those users should be able to press Alt+A in the Overlay as well so that they don't need to "learn" new key combinations

This issue was originally brought up by user u/n4te on [reddit](https://www.reddit.com/r/eclipse/comments/1dle5ts/new_find_dialog/)

**Comment by HeikoKlare** [comment]
There are already shortcuts for the search options, which should also be made configurable in the future (#2015). In order to not pollute the editors/overlay with shortcuts (in particular after #2254 and since they are currently not configurably mapped to actions and thus may be conflicting with other actions), we agreed to not implement this but rather keep the shortcuts that are explicitly defined and visible (in tooltips) and improve the possibilities with customizability of the shortcuts.
