### ISSUE TITLE
Find/replace overlay: border size

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#2194]
Very minor issue:
On windows, default light theme: the inner border size of  the overlay search is unbalanced if (and only if) used on a read only document like a .class file. On the left it is 2 pixels, on the right it is 3 pixels. Screenshot:
![image](https://github.com/user-attachments/assets/b7b137fa-9207-4383-92e8-a8a94d79d5a7)
@Wittmaxi

**Comment by Wittmaxi** [comment]
occurs on Ubuntu too
![image](https://github.com/user-attachments/assets/39239f79-e75d-431b-b018-ceea4edb9aee)

**Comment by HeikoKlare** [comment]
This always occurs if the replace toggle is not visible, e.g., also when it is hidden because the overlay is too small:
![{134CA761-EF2D-4F5E-BE9E-A4863C54004D}](https://github.com/user-attachments/assets/660148b8-6d44-4a54-b325-8d55aead1a38)

Reason is that the container grid layout always expects two colums but when the replace toggle is hidden only one exists, leading to an empty grid column.
