### ISSUE TITLE
Find/replace overlay: text field heights

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#2195]
minor issue, just looks ugly:
the replace-field is 2 pixel higher then the find-field:
![image](https://github.com/user-attachments/assets/be6aab68-c94c-4ecd-9946-09bc477932e8)
![image](https://github.com/user-attachments/assets/d52913cb-c679-4268-9d0a-06e84232b45a)
@Wittmaxi

**Comment by HeikoKlare** [comment]
Looks like this one has implicitly been fixed by one of the recent changes to the overlay, probably #2254:
![image](https://github.com/user-attachments/assets/6378270d-a689-404c-acc8-5827dd4df498)

Thus, closing this issue as fixed.
@jukzi if I missed something and this issue is still present, feel free to reopen.
