### ISSUE TITLE
Find/replace overlay: repeated ENTER has no effect in regex mode

### ISSUE THREAD

**Issue by nettozahler** [eclipse-platform/eclipse.platform.ui#2203]
In NON-regex (standard) mode one can simply add a phrase in the search and replace fields and change one occurrence after the other by pressing ENTER repeatedly. But this does not work for me in regex mode. Here hitting ENTER has no effect and I must use the "arrow down" button to jump to the next occurrence each time. 

I think there is no need to describe the bug in more detail because @HeikoKlare could already reproduce it and confirmed this being a bug. 

Let's make sure issue is not already fixed in latest builds first.
- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce
From a fresh installation and clean workspace:
Use find/replace overlay as described above in regex mode and hit ENTER key repeatedly which has no effect.

## Tested under this environment:
* Win11
* Eclipse SDK
Version: 2024-09 (4.33)
Build id: I20240731-1800

## Community
- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by HeikoKlare** [comment]
Thank you for reporting and documenting the issue, @nettozahler!

While working on the fix and adding regression tests, I found that the cause is that replace operations were not able to perform search operations anymore when regex and incremental search mode were activated. This affects more than the described case, e.g., also the existing find/replace dialog when having regex and incremental mode enabled as well as the ability to do a simple replace after a previous find even though the selection in the editor has changed meanwhile. Since that was existing functionality of the find/replace dialog, it was a regression compared to the previous release. I have created #2205 with a low-risk fix to still be applied for the upcoming 2024-09 release.
