### ISSUE TITLE
Find/Replace Overlay:  History missing

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#2291]
History is only added when i hit RETURN. but since the search already starts when i paste a String i do not need to hit RETURN. Instead i use the mouse to click into the editor where the result is found=> no history added. 
But later when i want todo the same search again i  am missing the last search i did.

Maybe add the current search to history when the overlay is left?

**Comment by HeikoKlare** [comment]
I understand the scenario and agree that such a search input should be added to the history. We should agree on a precise specification when we expect something to be added to the history. Since the overlay has incremental search enabled by default (other than the existing dialog), adding every searched term to the history is inappropriate, as typing "test" would result in history entries "t", "te", "tes" and "test". The current behavior should be consistent with the existing dialog, even for incremental mode being activated (but probably not many people used that in the existing dialog).

> Maybe add the current search to history when the overlay is left?

This sounds like a reasonable proposal. I would give it a try and see if it behaves in a "natural" way. This means we would define that items are added to the history in these cases:
1. An explicit search operation is performed
2. The overlay loses focus (or is closed) after an "implicit" search operation (via search-as-you-type) has been performed

**Comment by jukzi** [comment]
yes, lets try that.
