### ISSUE TITLE
Toolbar buttons in views disappear after resetting perspective

### ISSUE THREAD

**Issue by sbaranov-parasoft** [eclipse-platform/eclipse.platform.ui#230]
Observed in Eclipse 4.23, 4.24, but not in older versions, such as 4.16

To reproduce:
- Open Eclipse Java perspective 
- Choose Window->Perspective->Save Perspective As...
- Keep the original name (Java) or set a new name, e.g. "Java 2"
- Choose Window->Perspective->Reset Perspective
- Observer buttons in view toolbars disappear, e.g. the Task List view, the Outline view, etc.

![buttons](https://user-images.githubusercontent.com/30443426/181122393-e68e1167-15da-405a-80ac-9d4746f1b7c8.png)
View toolbar before resetting the perspective
![buttons-disappear](https://user-images.githubusercontent.com/30443426/181122484-3ab868c6-91c5-49f3-9774-315aed82bee8.png)
No toolbar/buttons after resetting the perspective

Restarting Eclipse causes the toolbar to reappear

**Comment by CruzeBlade** [comment]
Hi, I'm having the same issue. It would be great, if this could be fixed.

**Comment by iloveeclipse** [comment]
Can't reproduce on default SDK, 4.28 master.
Looks like you use some extra theming plugin. 
Please provide steps to reproduce **without** any 3rd party plugins installed.

**Comment by CruzeBlade** [comment]
It happens with clean installations of the Eclipse IDE too. I have downloaded [Eclipse IDE for Java Developers](https://www.eclipse.org/downloads/packages/release/2023-03/r/eclipse-ide-java-developers) and [Eclipse IDE for RCP and RAP Developers](https://www.eclipse.org/downloads/packages/release/2023-03/r/eclipse-ide-rcp-and-rap-developers). In both version this happens. I have also toggled theming on and off, and it happens in both cases.

Here is a list of all the plugins installed:
![image](https://user-images.githubusercontent.com/37212628/230009934-326a7fab-a969-4678-8674-47fd3a04dd83.png)

And here the about eclipse dialog:
![image](https://user-images.githubusercontent.com/37212628/230010133-f632163d-b0e6-45ad-a00f-a0d50fb1f781.png)

Thank you for having a look at this issue, I really appreciate it.

**Comment by merks** [comment]
I just downloaded that from scratch and modified the perspective layout:

![image](https://user-images.githubusercontent.com/208716/230011753-08bd45c4-8f79-4e6b-bec9-6fdbbd55217f.png)

Then I did a reset and afterwards everything looks fine:

![image](https://user-images.githubusercontent.com/208716/230011923-e3768892-53e4-4fda-b274-b67265af86e5.png)

But my icons look different from yours suggesting you've installed something else that provides different icons.

I'm on Windows 10...

**Comment by CruzeBlade** [comment]
Hi, my icons look the same as yours. It is important to save as a new perspective and reset the new perspective afterwards. OP has already provided a detailed explanation on how to reproduce the bug. 

I'm also on Windows 10 this hopefully should not make a difference.

**Comment by iloveeclipse** [comment]
> It is important to save as a new perspective and reset the new perspective afterwards

Yep, that is important indeed! I can reproduce now on latest master with default Java perspective.

**Comment by CruzeBlade** [comment]
Oh ok, great. I have just recorded a small demonstration of the issue, I hope this helps ( at least the others xD ) reproducing it: 
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/37212628/230020861-3e8e68f1-2689-473a-bb22-768bb9bcbd06.gif)

**Comment by benken-parasoft** [comment]
It is important to follow the reproduction steps as original described.  In particular, this issue happens when you reset a **custom** perspective.  You must first create a custom perspective (Choose Window->Perspective->Save Perspective As...).

It is common for developers to define their own custom perspectives and not use built-in ones.  If the developer (me) messes up their perspective layout by accident then they now have to restart the entire IDE after clicking "Reset Perspective" to restore the toolbar.

**Comment by iloveeclipse** [comment]
Perspective customization and related code is a nightmare, and this area is not anything I personally would like to look anytime soon.

Help is welcome, it would simplify our life if we could find for example in which release regression occured first.

**Comment by benken-parasoft** [comment]
>  it would simplify our life if we could find for example in which release regression occurred first

Based on our past observations, this must have regressed sometime between 4.16 and 4.23.  We had an Eclipse application based on 4.16 because of a Java 8 requirement.  Last year, after dropping support for Java 8, we updated to 4.23 at which point we discovered the regression.

**Comment by oleosterhagen** [comment]
In older Eclipse releases, before commit 9b03a05a3907988a1a8f381e925471569875cba1, toolbars where recreated in `StackRenderer.adjustTopRight(CTabFolder)` while adding the restored elements from the dummy perspective to the real perspective in the workspace:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/74e420dfd4fcb9646f54060b080f9cdd94bd15c4/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/StackRenderer.java#L808-L811

So, the toolbar later will be correctly re-parented to the composite control for the toolbars on the top right corner of the new tab folder:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/74e420dfd4fcb9646f54060b080f9cdd94bd15c4/bundles/org.eclipse.e4.ui.workbench.swt/src/org/eclipse/e4/ui/internal/workbench/swt/PartRenderingEngine.java#L586-L587

After the mentioned commit, toolbars are handled differently and no re-parenting occurs.

The problem does not happen with the **predefined perspectives** like the _Java Perspective_. Because these perspectives have no initial selected tab in the model, the framework selects the first one in `LazyStackRenderer.postProcess(MUIElement)`:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/7481e49c225cccbb2bd6714584087f2940fc754b/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/LazyStackRenderer.java#L118-L124

As a side effect of this selection the toolbar is first hidden in `LazyStackRenderer.childRendered(MElementContainer, MUIElement)` and later restored in `LazyStackRenderer.showElementRecursive(MUIElement)`. This visibility change finally triggers the PartRenderingEngine.subscribeVisibilityHandler(Event) where the toolbar is re-parented:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/7481e49c225cccbb2bd6714584087f2940fc754b/bundles/org.eclipse.e4.ui.workbench.swt/src/org/eclipse/e4/ui/internal/workbench/swt/PartRenderingEngine.java#L213-L217

#767 ensures that the toolbar is re-parented even without a selection/visibility change event.

**Comment by iloveeclipse** [comment]
@oleosterhagen : thanks!

**Comment by wimjongman** [comment]
For people stuck on a specific version, here is a workaround after you did a perspective reset and want to get the toolbar(s) back.

### Possible Workarounds
* Move the view in the viewstack to a different position in the same viewstack.
* Close the views without toolbars and then reset the perspective again
