### ISSUE TITLE
[Find/Replace] changed search string is ignored by search dialog

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#2322]
I believe this is a regression in the recent code related to Find/Replace.

I'm using "old" Find/Replace dialog, latest SDK build I20240923-1800.

1) Open FindReplaceDialog.java in the IDE
2) Select `findReplaceLogic` at line 83 and trigger Ctrl+F to open find/replace dialog
3) Click once on Find => should jump to line 107 and highlight `findReplaceLogic` string (OK).
4) In the find/replace dialog, type "." after `findReplaceLogic` search text and click on "Find"
5) The dialog **continues to search with the old search string** and selects next `findReplaceLogic` occurrence on line 108.
6) Change search direction to "backward" and click "Find" two times => we are at line 83 again, where **no match** for `findReplaceLogic.` should be found!

![image](https://github.com/user-attachments/assets/ee62c851-62c5-4a0f-a8d8-8ca4787c8cd9)

**Comment by iloveeclipse** [comment]
@Wittmaxi, @HeikoKlare : FYI. 

I didn't investigated if this related to the overlay work, if yes, probably should be added to https://github.com/eclipse-platform/eclipse.platform.ui/issues/2021

**Comment by HeikoKlare** [comment]
Thank you for the detailed reproduction description. I expect this to be a regression of #2209. I will try to have a look as soon as possible.

**Comment by HeikoKlare** [comment]
The issue is not reproducible in MacOS. Since the search string in the `FindReplaceLogic` is updated after changing the text field (via reacting to the modification event), it might be related to event handling in GTK, i.e., a Linux-specific issue. I will further investigate once I have access to a Linux system again (probably at the end of the week). I have added this issue to the umbrella ticket with high prio.
