### ISSUE TITLE
Switching Perspective should close hidden Perspective

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#248]
When the user switches the perspective by clicking on another perspective the former is not closed but only hidden - and running (not disposed).
![image](https://user-images.githubusercontent.com/51790620/183080296-512670ea-b9ac-4f71-b4de-d62612efd21c.png)
Since some Views (like "Git Staging" or "Debug") can be really slow with mass data that is undesirable for the user. 

After using eclipse for ages i just learned - by looking at the code - the user could close the unneeded view manually - but why is that not done automatically? Counter intuitive.
![image](https://user-images.githubusercontent.com/51790620/183081991-b02b7c37-b348-40f1-82ea-00a67aeee52c.png)
WDYT?
Or should all slow Views implement a listener to see if they are still visible? awkward

**Comment by laeubi** [comment]
As far as I know `close` behaves different, e.g. removing the perspective from the list of displayed perspectives and most likely reset the state somehow, I think not disposing things is intentional so if I switch back+fourth it happens fast.

> some Views (like "Git Staging" or "Debug") can be really slow with mass data

Maybe this should then addressed there, e.g. by properly disposing no longer needed data, using lazy tree/tables and so on.

**Comment by merks** [comment]
Yes, just closing views will be unexpected and will lose state.  And some views are saveable...

**Comment by iloveeclipse** [comment]
"Closing" views on switching perspective could break lot of code I guess and would surely break user experience (because switching back the views will be not there). 

What you probably want is to "dispose" views and replace them with "placeholders", so on switching back they are restored.

This would probably work, but again, will most likely break existing products and user experience.

Just assume you have complex "memory profiling" perspective where you have opened all the memory snapshots etc, spent some time analyzing all that and just switches to "debug" perspective to validate your assumptions. 

After that, switching back would show you "empty" memory analysing perspective with all the selections/tables etc gone, showing some initial state. Many views cannot persist state simply because they work on in-memory data which need to be loaded/created first, so simply disposing them would lost the expected view state.

I know the problem with "too active" views, and the extra code needed to track "I'm visible?" state. One doesn't even need to switch to another perspective - just open other view in the same stack. Should the view be "muted" here too? May be yes, may be no, but surely it shouldn't be disposed or closed.

So at the end, you probably want to provide some easy to use API for views that could be implemented to "suspend view activity" as long as view is not visible, without extra code for various listeners.

**Comment by jukzi** [comment]
OK, thanks for all the feedback. do we have a good example how to suspend while invisible?

**Comment by laeubi** [comment]
> So at the end, you probably want to provide some easy to use API for views that could be implemented to "suspend view activity" as long as view is not visible, without extra code for various listeners.

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=572730

**Comment by merks** [comment]
I don't know of an example.  There is org.eclipse.ui.IWorkbenchPage.isPartVisible(IWorkbenchPart) but as you assume, one would need a listener for state changes...

**Comment by iloveeclipse** [comment]
> do we have a good example how to suspend while invisible?

Look at type hierarchy of `org.eclipse.ui.IPartListener2`. For example, `org.eclipse.help.ui.internal.views.HelpView` view hooks/unhooks itself on visibility changes.
