### ISSUE TITLE
Inconsistent display of menu tooltips

### ISSUE THREAD

**Issue by ewillink** [eclipse-platform/eclipse.platform.ui#2483]
I found that some of my tooltips were not being shown and after fixing some bad XML (the editor does not diagnose a gratuitous extra premature ">") I found that just changing the org.eclipse.ui.menus extension point in plugin.xml from 
`		<menuContribution locationURI="popup:org.eclipse.ocl.examples.ui.Menu?after=show">
`
to
`		<menuContribution locationURI="popup:org.eclipse.ocl.examples.ui.Menu?after=load">
`
could make the missing tooltip visible.

Debugging by setting a breakpoint at line 1353 of Menu.class
`			boolean success = OS.GetMenuItemRect (0, selectedMenuItem.parent.handle, selectedMenuItem.index, rect);
`
`			if (!success) return null;
` 
revealed two problems. a) when success is true, b) when success is false.

The first (success true) is reprodible on a basic Eclipse platform. Many menu entries have no tooltip. e.g. Help->Tip of the Day however debugging reveals this is because itemToolTip is null. Surely a missing tooltip should be 'inferred' as the label as is often the case already.

The second (success false) appears to be related to plugin.xml extension of a dynamically defined menu - not reprodicible on a basic platform.

In so far as I can debug this, I suspect that the selectedMenuItem.index argument to OS.GetMenuItemRect fails to account for separators and/or invisible entries and/or sub-menus.

'Repro'. The problems I experience are reproducible using the context menu of the Sample Ecore Editor. Team->Show Local History has a tooltip that is not displayed because success=false. (A repro using my released OCL code will just uncover downstream effects of the bad XML.)

**Comment by BeckerWdf** [comment]
> I found that just changing the org.eclipse.ui.menus extension point in plugin.xml from
> ` <menuContribution locationURI="popup:org.eclipse.ocl.examples.ui.Menu?after=show"> `
> to
> ` <menuContribution locationURI="popup:org.eclipse.ocl.examples.ui.Menu?after=load"> `
> could make the missing tooltip visible.

I don't see a difference.

**Comment by ewillink** [comment]
Indeed. The miniscule, should-be-irrelevant, difference is the separator in:

```
<extension point="org.eclipse.ui.menus">
		<menuContribution locationURI="popup:org.eclipse.ui.popup.any?after=additions">
         <menu id="org.eclipse.ocl.examples.ui.Menu" label="%MF_OCL" icon="icons/ocl16.gif">
            <separator name="load" visible="true"/>
            <separator name="save" visible="true"/>
            <separator name="set" visible="true"/>
            <separator name="show" visible="true"/>
			<visibleWhen checkEnabled="false">
				<test property="org.eclipse.ocl.examples.ui.resourceSetAvailable" forcePluginActivation="true"/>
			</visibleWhen>
         </menu>
      </menuContribution>
   </extension>
```
Once M3 is out I should be able to post a repro that avoids project GIT repos or bad XML.

**Comment by merks** [comment]
In a debug launch, it worked correctly for the text editor.  But if EGit is included in the launch it doesn't work.  I can see it gets to this state:

So it knows the selected item and it is the one with a tool tip text, but the index of that item is 18 even though it is the first item in the menu (which unfortuately is black during the screen capture:

![image](https://github.com/user-attachments/assets/912845bf-3d9b-4cd4-b99d-f2d584642864)

So it seems to me the problem is caused by the wrong index, likely because of items that have been removed or filtered or hidden separators.  When EGit is not included in the launch, the index is zero which makes sense because it's the first visible item in the menu.  I don't have time right now to debug further...

**Comment by merks** [comment]
I'm not suggesting this is the fix, but if I change the code in org.eclipse.swt.widgets.Menu.wmTimer(long, long) like this:
```
	LRESULT wmTimer(long wParam, long lParam) {
		if (wParam == ID_TOOLTIP_TIMER) {
			POINT pt = new POINT();
			OS.GetCursorPos(pt);
			if (selectedMenuItem != null && selectedMenuItem.parent != null) {
				RECT rect = new RECT();
				MenuItem[] items = getItems();
				for (MenuItem menuItem : items) {
					System.err.println(menuItem.index + ":" + menuItem.getText() + "->" + menuItem.getToolTipText());
				}
				int index = Arrays.asList(items).indexOf(selectedMenuItem);
				// boolean success = OS.GetMenuItemRect (0, selectedMenuItem.parent.handle,
				// selectedMenuItem.index, rect);
				boolean success = OS.GetMenuItemRect(0, selectedMenuItem.parent.handle, index, rect);
```

Then the tool tip shows, I believe because the index is correct relative to the actual menu items current in in the menu.

With the print statement, without EGit deployed, I see this:
```
0:Show Local &History->Show Local &History
1:->null
2:Appl&y Patch...->Apply a patch to one or more workspace projects.
3:->null
4:&Share Project...->Share the project with others using a version and configuration management system.
```

With EGit's feature in the launch I see this instead:
```
18:Show Local &History->Show Local &History
24:->null
26:Appl&y Patch...->Apply a patch to one or more workspace projects.
35:->null
36:&Share Project...->Share the project with others using a version and configuration management system.
```
So it's quite clear that the menuItem.index value is simply wrong and this is the reason why the tool tip associated with that menu item is not shown.

I'm out of time again for now...

**Comment by ewillink** [comment]
Thanks. I don't recognize the black area, but 

> clear that the menuItem.index value is simply wrong

seems very similar to my suspicion. I won't struggle to provide a rival M3 repro using my OCL code.

**Comment by merks** [comment]
> I won't struggle to provide a rival M3 repro using my OCL code.

Indeed. I can reproduce the problem and will continue to dig.

**Comment by merks** [comment]
I think the design is just wrong/broken.  The MenuItem.index is initialized upon construction and is never updated nor maintained.  But a MenuItem.dispose can obviously change every other MenuItem's actual index in the disposed MenuItem's containing Menu.

**Comment by HeikoKlare** [comment]
If I am not mistaken, this has been fixed via https://github.com/eclipse-platform/eclipse.platform.swt/pull/1575
Or is there something else to do for this, @merks?
