### ISSUE TITLE
Disable icons in the dark theme by default

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#2554]
I think the new dark theme from https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114 looks way better WITHOUT icons

![image](https://github.com/user-attachments/assets/54642f15-2bad-4640-8e91-8ec7b04e594a)

![image](https://github.com/user-attachments/assets/7fb1cb4c-2310-4e69-9ec5-c76df22b61b1)

@BeckerWdf @mvm-sap @thomasritter WDYT? Should we active this setting by default in the dark theme?

**Comment by vogella** [comment]
Requires https://github.com/eclipse-platform/eclipse.platform.ui/issues/2553 so that the user can easily find this setting.

**Comment by BeckerWdf** [comment]
> looks way better with icons

with or without icons?

**Comment by thomasritter** [comment]
To me the icon settings is based on personal preference. Personally, I like all themes more without the icons but looking at the screens of the developers in our department I can see that the appearance settings are all over the place. Some switch off the icons some do not.

- Appearance settings are deeply personal. I do not think developers will like if we switch something automatically
- The current UI does not suggest that the settings are connected. In my opinion it would confuse developers
- Switching off the icons actually means switching important Eclipse features like in the JUnit view which shows you test execution progress & status via icon decorators. Same with the problems view which indicates whether errors/warnings exist

To me the solution for this problem is still a getting started pop up/page which comes up after you first launch Eclipse. Nowadays, it is pretty much standard to ask for light/dark theme at first start up. On that page if the user picks the dark theme an additional option could be the icon switch. We discussed this page during the Eclipse Community Day in Rot and the general feedback was positive but we have not started working on it. The goal of the page is to promote the new visual options and make sure they are actually being used. Here an example from VSCode.

<img width="804" alt="image" src="https://github.com/user-attachments/assets/e794c94c-60dc-4551-83a1-106607050947">

**Comment by vogella** [comment]
> Some switch off the icons some do not.

In my experience most users don't know our available options. For example, I also did not actively remembered that Eclipse now has this option to turn off icons, I was reminded by a participant in the training. By changing the default in the dark theme and by making this option easy to find, we should allow users to make their personal setting.

But of course the idea of having a pop-up or configuration screen for this is a great one.  IIRC code puts its into the editor area, which I think is a very good way (IMHO your welcome screen should also behave like this and opens up in the editor area instead of blocking the whole screen).

**Comment by vogella** [comment]
Btw. IIRC @merks implemented a "Hello new user - Let us implement your new workspace settings" in EPP.  IIRC this feature was disabled by all EPP not sure why.

Maybe because it was a blocking dialog which you had to finish before starting Eclipse. And this is very annoying for users like me.  IMHO a non-blocking "editor" would be easier to accept.

**Comment by merks** [comment]
Firstly, some people were horrified about how it looked.  You can still see it via this button:

![image](https://github.com/user-attachments/assets/523cd032-73d3-4036-86fd-b0ffb06497bf)

The options are really out-of-date now, so it would need an overhaul.

There's always the welcome screen that can have button. links and such.  Unfortunately in the end, users don't read what's presented to them, they seek the fastest way to get rid of what is in front of them (even if that involves hitting an OK button that will do something they've not bothered to understand), and finally, the more superficial something is, the more everyone has divergent strong opinions.  😜

**Comment by vogella** [comment]
The welcome screen has a critical issue: it blocks the UI. Naturally, users will want to dismiss it immediately.

From my experience, users starting with a new tool typically want to explore and use it first before considering any configuration options. For example, during my 5-day IDE or RCP training sessions, if I begin by showing participants how to configure Eclipse to automatically terminate a running instance, no one pays attention. However, when I demonstrate this setting after 1-2 days of using Eclipse, many are thrilled to learn it because they’ve already experienced the inconvenience of manually stopping the running instance.

This highlights why a configuration option embedded in an editor is far more effective than one presented upfront. Users can leave the editor open and return to it later when they feel ready to explore those options. Similarly, any news or tips the welcome screen offers should not disrupt the user experience but instead be accessible when the user is ready.

**Comment by vogella** [comment]
Lets close this, we do not want to disable icons by default but maybe give the user an option to configure this. But that is anothe request.
