### ISSUE TITLE
New Wizard Dialog should also include Categories into Filter

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#2576]
If I search in the new project wizard for a category nothing is shown:

![image](https://github.com/user-attachments/assets/449c1199-c3f8-4122-bf36-794cb19b76d4)

I would expect that all entries in the category are shown.

![image](https://github.com/user-attachments/assets/c96cf60f-b8e8-4533-922d-8d51a9fdf338)

cc @ptziegler as he recently looked at the FilteredTree implementation.

**Comment by jukzi** [comment]
+1, same for "Show View" Dialog:
![image](https://github.com/user-attachments/assets/56f48145-0168-47af-a482-51214a5475cf)

![image](https://github.com/user-attachments/assets/a6333418-3ff0-4c9d-a782-ddb531af4868)

**Comment by ptziegler** [comment]
Based on a quick glance, I believe that this is a very old regression, rather than an enhancement, because in the original implementation, this used to work:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/c782ba355969e0ed75b579d6607cd0076f9fe397/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/dialogs/ViewPatternFilter.java#L42-L78

But then broke as part of https://github.com/eclipse-platform/eclipse.platform.ui/commit/7275893613e8050290cac3c970e14f9889b87b73

In principle, it should be sufficient to simply override `ìsParentMatch(...)`, because the default implementation is not the desired behavior:

> Check if the parent (category) is a match to the filter text. The defaultbehavior returns true if the element has at least one child element that is amatch with the filter text.Subclasses may override this method.

I can have a look later but at least it apears to be a trivial change...

**Comment by vogella** [comment]
> I can have a look later but at least it apears to be a trivial change...

Awesome, thanks @ptziegler

**Comment by vogella** [comment]
The fix does not work for me in:

Eclipse SDK
Version: 2025-03 (4.35)
Build id: I20241208-1800
OS: Linux, v.6.8.0-49-generic, x86_64 / gtk 3.24.41
Java vendor: Ubuntu
Java runtime version: 21.0.5+11-Ubuntu-1ubuntu124.04
Java version: 21.0.5


![image](https://github.com/user-attachments/assets/d301f4c9-af5d-4cc4-b050-33dff57a16c0)

**Comment by ptziegler** [comment]
The "New" wizard has its own [pattern filter](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.workbench/eclipseui/org/eclipse/ui/internal/dialogs/WizardPatternFilter.java) that also needs to be adapted.

**Comment by vogella** [comment]
I assume the same for the Show View dialog (in which filtering by category is also not working)? Could you also provide PR for these two dialogs @ptziegler?

**Comment by ptziegler** [comment]
The "Show View" dialog is using the [ViewPatternFilter](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.workbench/eclipseui/org/eclipse/ui/internal/dialogs/ViewPatternFilter.java), which was adapted and where the filtering is working.

![image](https://github.com/user-attachments/assets/4c1219e5-43a4-44ef-9d80-97f62af91703)

> Could you also provide PR for these two dialogs

https://github.com/eclipse-platform/eclipse.platform.ui/pull/2602

**Comment by vogella** [comment]
Awesome @ptziegler
