### ISSUE TITLE
Constant failing of the tycho-apitools-plugin for Linux in the GH actions

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#2603]
Sorry if that has already been reported but I could not find a issue about it in this repo.

The Linux verification fails constantly for PR in this repo 

````
Error:  Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.10:verify (verify) on project org.eclipse.ui.views.properties.tabbed: Execute ApiApplication failed: InvocationTargetException: Component 'Tabbed Properties View' in the baseline 'workspace' is disposed [main]: Component was disposed here [Worker-2: Updating plug-in dependencies] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.10:verify (verify) on project org.eclipse.ui.views.properties.tabbed: Execute ApiApplication failed
````

@HannesWell @laeubi is this a known issue?

**Comment by laeubi** [comment]
This also happen in Jenkins sometimes, it seems to be an timing issue, I now added the follwoing improvements / workarounds:

- https://github.com/eclipse-tycho/tycho/pull/4575
- https://github.com/eclipse-tycho/tycho/pull/4561

once they are available the failure should hopefully be gone, I tried to debug this a bit locally but due to it depends on the timing its quite hard to guess whats really going on.

So I added a breakpoint at the "disposed here" place and disposed the baseline manually as a test, then I see that after the second run the first breakpoint is never hit again and the retry actually works.
