### ISSUE TITLE
StagingView/ToolBarManager: SWT Resource was not properly disposed

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#271]
i closed the staging view and git perspective:

java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:250)
	at org.eclipse.jface.resource.DerivedImageDescriptor.internalCreateImage(DerivedImageDescriptor.java:89)
	at org.eclipse.jface.resource.DerivedImageDescriptor.createResource(DerivedImageDescriptor.java:51)
	at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:55)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:88)
	at org.eclipse.jface.resource.LazyResourceManager.create(LazyResourceManager.java:103)
	at org.eclipse.jface.resource.LocalResourceManager.allocate(LocalResourceManager.java:72)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:88)
	at org.eclipse.jface.resource.ResourceManager.createImageWithDefault(ResourceManager.java:195)
	at org.eclipse.jface.action.ActionContributionItem.updateImages(ActionContributionItem.java:1017)
	at org.eclipse.jface.action.ActionContributionItem.updateToolItem(ActionContributionItem.java:776)
	at org.eclipse.jface.action.ActionContributionItem.update(ActionContributionItem.java:739)
	at org.eclipse.jface.action.ActionContributionItem.fill(ActionContributionItem.java:350)
	at org.eclipse.jface.action.ToolBarManager.update(ToolBarManager.java:358)
	at org.eclipse.jface.action.ToolBarManager.createControl(ToolBarManager.java:130)
	at org.eclipse.egit.ui.internal.staging.StagingView.createUnstagedToolBarComposite(StagingView.java:1741)
	at org.eclipse.egit.ui.internal.staging.StagingView.createPartControl(StagingView.java:902)

eclipse.buildId=4.23.0.I20220308-0310

**Comment by trancexpress** [comment]
@jukzi which EGit version is in your Eclipse? From the stack trace it seems unlikely there is a problem in JFace, more likely the problem is in EGit UI code. Unfortunately I don't see where, from the stack trace. In current EGit, all the icons are created in a static initializer... it would be odd if they were dereferenced. There aren't recent changes in ```StagingView.createUnstagedToolBarComposite()``` either, that I see...

**Comment by jukzi** [comment]
6.1.0.202203080745-r	org.eclipse.egit
I could not see an error in the StagingView code so i thought i would be platform UI, reference counting something.

**Comment by trancexpress** [comment]
I'm not finding a problem in the EGit code either. EGit is using image descriptors, I initially thought its creating images directly. It also doesn't look like ```ToolBarManager``` (that EGit creates on the stack trace) needs to be explicitly disposed.

So maybe a problem in ```AbstractResourceManager.RefCount``` handling and code near it, as you say (maybe the destroy call is missing?). I don't remember seeing such stack traces where the problem was in platform UI code, but maybe the bug is just rare. I also don't find recent code in the area... just some style changes from https://bugs.eclipse.org/bugs/show_bug.cgi?id=567905.

Do you remember the state of the UI, roughly? Did you have any EGit views open in other perspectives before you closed the staging view in the Git perspective (I assume the view was in the Git perspective when you closed it?) and then closed also the Git perspective?

**Comment by jukzi** [comment]
i had that IDE instance open for several days ... don't know what i did. I could not straight forward reproduce it with manual GC. yea may be rare multithreading(?) bug in either the IDE - or in the NonDisposeTracking (i know that is not 100% bullet proof).

**Comment by trancexpress** [comment]
AFAIK the operations should be single-threaded, in the UI thread. I don't think its a multihreading problem, SWT should throw exceptions on non-UI thread access (and here, the SWT image needs to be created and disposed, both are SWT operations). More likely some dispose/destroy call is missing, because reasons.

The reference counting is done with a counter and a map, and the non-disposed objects tracking is done with ```finalize()```. So the references to the image were removed from the map (and whichever other code was referencing the image) but the counter was not 0. Maybe that narrows the potential causes... I'll try to take a look this week.

**Comment by jukzi** [comment]
Even if all of eclipses code is running in a single Display thread, the finalisation (incl. NonDisposeTracking ) runs in a separate thread. So there is a small chance of MT issue.
Another theoretical error: if the staging view shares the Image with another UI component, then the NonDisposeTracking may lead to the wrong creation since the other UI component may have forgotten to dispose - undetected due to reference counting.

**Comment by trancexpress** [comment]
> Even if all of eclipses code is running in a single Display thread, the finalisation (incl. NonDisposeTracking ) runs in a separate thread. So there is a small chance of MT issue.

I checked the code that should theoretically lead to this problem:

```
		// Find the existing resource
		RefCount count = map.get(descriptor);
		if (count != null) {
			// If the resource exists, decrement the reference count.
			count.count--;
			if (count.count == 0) {
				// If this was the last reference, deallocate it.
				deallocate(count.resource, descriptor);
				map.remove(descriptor);
			}
		}
```

If the element was removed from the map before the dispose call (should be done in the deallocate call), I assume with very aggressive GC you are right. But the element is removed from the map after the deallocate call, so a reference to the image object remains via ```AbstractResourceManager.RefCount``` (and in theory via the image descriptor) until after the image is disposed.

Maybe the deallocate call itself doesn't actually dispose the image, I see e.g. ```OriginalImageDescriptor.destroyResource(Object)``` does reference counting as well...

> Another theoretical error: if the staging view shares the Image with another UI component, then the NonDisposeTracking may lead to the wrong creation since the other UI component may have forgotten to dispose - undetected due to reference counting.

Will have to check code for this. The stack trace shows this method: ```DerivedImageDescriptor.internalCreateImage(Device)```

```
	private final Image internalCreateImage(Device device) {
		Image originalImage = original.createImage(device);
		Image result = new Image(device, originalImage, flags);
		original.destroyResource(originalImage);
		return result;
	}
```

So it seems unlikely something in EGit is sharing the image descriptor and is so causing the problem. Since there the image descriptors are URL image descriptors, and (I think, after looking  at the code above) their image is immediately disposed. Its this ```Image``` object created by the method above that is leaking. Will have to check callers.

**Comment by jukzi** [comment]
mystery remains unsolved, as unclear how to reproduce.
