### ISSUE TITLE
Terminated tasks stay hanging in Progress view

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#342]
Since some latest changes on Progress view in 4.26 I observe various job entries staying "hanging" in the Progress view.
I can click on "Black cross" icon on the entry to "remove it from view", they are removed ... but appear again as soon as I click on "Remove All" button in the Progress view.

Before:
![image](https://user-images.githubusercontent.com/964108/191056174-a0626d15-2860-41e9-a425-3a52341e1308.png)

after "remove from view":
![image](https://user-images.githubusercontent.com/964108/191056396-d34ce03d-6d09-437e-86b3-7d2fa0535be4.png)

and back to live after "Remove All":
![image](https://user-images.githubusercontent.com/964108/191056547-f8a8a5e4-cb8d-410c-a042-450682aa9e88.png)

I assume https://github.com/eclipse-platform/eclipse.platform.ui/pull/308 could be the root cause for the regression.

**Comment by iloveeclipse** [comment]
https://user-images.githubusercontent.com/964108/191501730-fa5472b1-a204-4ff0-a6df-8574d67a4cd8.mp4

@jukzi : could you please check this? 
I assume something with handling of cancelled job entries is wrong now.

**Comment by jukzi** [comment]
How to reproduce? I do not see such behavior even if i cancel jobs or press the remove all button. do you have "Show slepping" preferences enabled or disabled?

**Comment by iloveeclipse** [comment]
> How to reproduce?

Try to work with latest SDK builds :-)
Sooner or later some job will "hang" in the Progress view.

My typical workflow includes starting latest SDK nightly build with existing SDK workspace with almost all of SDK projects opened. That alone produces lot of build related jobs because of the platform change.
After that "pull all" on all SDK repos produces another batch of jobs.
And typically I have to pull & debug PR's, which again causes various jobs.
Somewhere in that workflow some job will "hang".

> do you have "Show slepping" preferences enabled or disabled?

Enabled.

**Comment by jukzi** [comment]
I got one case where it showed the IOConsolePartitioner$QueueProcessingJob 3 times, and got the same behavior like you. 
I "removed" all items from the view and took a heapdump.
org.eclipse.ui.internal.progress.FinishedJobs was empty
![image](https://user-images.githubusercontent.com/51790620/191563331-694c8243-782e-47cb-b4b1-eea8bf002f9b.png)
 and DetailedProgressViewer.jobItemControls  was empty:
![image](https://user-images.githubusercontent.com/51790620/191563142-7720e0f8-6456-409a-af1a-eb74006678d6.png)

The GC root of the 3 Jobs was org.eclipse.ui.internal.progress.ProgressManager.runnableMonitors
![image](https://user-images.githubusercontent.com/51790620/191564550-5e8f4729-0c8f-4e58-aae1-1ef9eb765bfa.png)

I don't think this is related to my changes in the DetailedProgressViewer/JobInfo - it's just that ProgressManager says those jobs are still there and he does not use the JobInfo but the Job as key. 

My best guess is that the cancel event may be sometimes send in a strange order - (like the join() problem). And any further cancel() events from ProgressInfoItem.cancelOrRemove() (the action of the button) will be ignored from org.eclipse.core.internal.jobs.JobManager.cancel(InternalJob).

One might add the ProgressManager.checkForStaleness(Job) to org.eclipse.ui.internal.progress.ProgressManager.refreshJobInfo(JobInfo)? Hard to say because i have no deterministic reproducer.

**Comment by iloveeclipse** [comment]
> it's just that ProgressManager says those jobs are still there and he does not use the JobInfo but the Job as key.
> 
> My best guess is that the cancel event may be sometimes send in a strange order - (like the join() problem).

May be same problem as https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/137
