### ISSUE TITLE
When starting eclipse, the progress bar does not indicate the current progress

### ISSUE THREAD

**Issue by natarol** [eclipse-platform/eclipse.platform.ui#459]
Normally, the loading plug-in should be displayed . 
But it is actually stuck in the "Starting Eclipse IDE"

**Comment by iloveeclipse** [comment]
If Eclipse finally starts, it is supposed to be an improvement (not showing individual plugins), @vogella could point to a bugzilla ticket that removed that.
If Eclipse hangs on startup, please create thread dump via jstack and attach it here.

**Comment by natarol** [comment]
I should have met this scene

"If Eclipse finally starts, it is supposed to be an improvement (not showing individual plugins)"

I don't know whether it is a bug or a configurable item

**Comment by jukzi** [comment]
Can reproduce - for me the progress only shows two states 0%, 50% -> gone:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/11805589-7408-4f22-a476-39b6cf023f5e)
That's barely worth an progress bar at all. And i don't consider it an improvement. @vogella also reported such behavior as a bug:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=497444
@natarol do you mind to investigate what was changed or even propose a fix? You might want to look around StartupProgressBundleListener

**Comment by elsazac** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/blob/35b967425bdefd37f3b7b3f7a8d93df37619e046/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/Workbench.java#L312-L320

There are multiple issues that I can see.
 - The progress bar is processed only in response to bundle events (and that too only for started bundles)
 - Part of the startup also has some heavy weight operation like post startup UI rendering in a separate thread which is not captured in the progress bar
 - The values of the progress made and the pending progress are currently hardcoded with magic numbers.

**Comment by laeubi** [comment]
@elsazac can you explain the issues you see in more detail?

> The progress bar is processed only in response to bundle events (and that too only for started bundles)

These are actually the ones blocking the startup, as we more and more remove bundle activators it might be that actually nothing is started at all and progress bar can only show little to nothing (instead the Ui should show up).

> Part of the startup also has some heavy weight operation like post startup UI rendering in a separate thread which is not captured in the progress bar

If something is already showing I think we don't need a progressbar on the splash screen, especially if it happens in the background

> The values of the progress made and the pending progress are currently hardcoded with magic numbers.

This is a common pattern if the total progress is not know, do you have any better idea how to know the total progress in advance? I think one can query the OSGi Framework to get a list of bundles that are marked for starting and the startlevels but I'm not sure its worth it as we just want the user give some feedback that"something" is happen, so maybe it is time to more show an intermediate progress instead of a progressbar that gives the impression we know it exactly.

**Comment by jukzi** [comment]
does anybody know how to launch a debugee that shows the progress bar?

**Comment by laeubi** [comment]
As far as I know this only works with remote debugging as the splash screen is provided by the native launcher.

**Comment by elsazac** [comment]
> @elsazac can you explain the issues you see in more detail?

 - First the progress bar is not showing progress proportionate to the total time.
 - The first half of the progress bar moves very fast while there is a visible delay in the second half.
 - even after the progress shows 100% there is a considerable pause time before the UI shows up
 
> If something is already showing I think we don't need a progress bar on the splash screen, especially if it happens in the background

agree , but if the progress is not moving and nothing is showing up, the user gets an impression that there is an unforeseen issue which causes delay in the startup leading to poor user experience 

> This is a common pattern if the total progress is not know, do you have any better idea how to know the total progress in advance? 

what I did is : 
 - got a count of the bundles in the first run
 - introduced two fields : `todo` and `done`, assigned with 100 and 0 respectively 
 - In each call back I reduced `todo` and increased `done` as a percentage of the bundle count
 - Used `todo` and `done` in the `submonitor`  

With these, I am able to see a little better progress bar. However,  as I mentioned,  the last part is still not great

**Comment by laeubi** [comment]
> First the progress bar is not showing progress proportionate to the total time.

Because we have no clue how long a bundle start takes this is not possible

> The first half of the progress bar moves very fast while there is a visible delay in the second half.

Yes that numbers are a bit heavy, maybe `subMonitor.setWorkRemaining(100).worked(1);`  gives a bit better visuals.

> even after the progress shows 100% there is a considerable pause time before the UI shows up

But thats something we can't really influence I think because the Splash is hidden wenn the application is started, so then only the application might be able to show additional "progress" (what might be hard to calculate as well).

> With these, I am able to see a little better progress bar. However, as I mentioned, the last part is still not great

The problem is that not all bundles are mandatory to be started, so this might give a poor result as well. Due to how OSGi works, I think one can't give good "progress" of startup in terms of numbers.

**Comment by laeubi** [comment]
@elsazac by the way if you want to just get more events what happening you could use these listeners there should be much more to "see" that just a bundle listener:

- https://docs.osgi.org/javadoc/r4v43/core/org/osgi/framework/FrameworkListener.html
- https://docs.osgi.org/javadoc/r4v43/core/org/osgi/framework/ServiceListener.html

That way you should also get notified about services that are created ...
