### ISSUE TITLE
Update to Eclipse 2022-12 breaks `Open Type` key binding

### ISSUE THREAD

**Issue by veita** [eclipse-platform/eclipse.platform.ui#513]
After updating to Eclipse 2022-12 the `Open Type` key binding <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd> was broken due to a duplicate binding to `Go to Symbol in Workspace`.

Deleting the binding for `Go to Symbol in Workspace` also deleted the binding for `Open Type`, so the correct binding (with `When: In Windows`) had to be restored manually.

It would probably better to not overload the most important key bindings by default.

**Comment by jukzi** [comment]
https://github.com/eclipse/lsp4e/issues/38

**Comment by mickaelistria** [comment]
This issue can, and probably should, be solved in JDT-UI by having the "Open Type" binding also defined in the "Editing Java Source" context.
The trick is that Platform will favor the command for the most specific context; the current collision is in the "in Windows" context, which is pertty vague but actually useful and not hurting outside of the editor (so we shouldn't remove it). If we re-define the "Open Type" command binding in the "Editing Java source" context, then it takes priority before the conflict and the "Open Type" opens when in Java editor.
You can workaround it manually: go to Preferences > General > Keys, find the "Open Type" shortcut, click "Copy binding" and recreate the binding for the same shortcut, but setting the "editing Java source" context; apply; enjoy the result in the Java editor.

**Comment by trancexpress** [comment]
> If we re-define the "Open Type" command binding in the "Editing Java source" context, then it takes priority before the conflict and the "Open Type" opens when in Java editor.

Presuming anyone actually applies this fix. What occurs when the Java editor doesn't have focus? Or the lsp4e command is active only while the Java editor has focus? I use open type from everywhere, not just the Java editor.

Or am I misunderstanding the proposal?

**Comment by mickaelistria** [comment]
> Or the lsp4e command is active only while the Java editor has focus? 

So far, LSP4E command is only handled when current selection is bound to a language server.
But I suspect this is likely to change one way or the other in the future, overall Ctrl+3 should be the one shortcut to rule them all when it comes to searching symbols from multiple sources. I'm not just certain yet it's an entirely good substitution to the current approach: if it is, LSP4E may even remove the "Open Symbols" command, if it's not, then this command may one day be always handled and return the symbols from all language servers independently of the selection...
But in any case, the best way to enforce one specific command takes precedence in 1 specific editor is what I mentioned above: binding the specific command with the specific context (that doesn't prevent to also bind the specific command with more generic context, but it does prevent more generic commands to be have same priority in the specific context)

**Comment by jukzi** [comment]
It's a shame LSP4E guys break the Java IDE but don't show any activity to fix it.

**Comment by mickaelistria** [comment]
> It's a shame LSP4E guys break the Java IDE but don't show any activity to fix it.

The only person who has shown concrete activity so far by spending some hours investigating the issue, finding some workarounds and recommended a solution is an LSP4E guy.

**Comment by szarnekow** [comment]
> I use open type from everywhere, not just the Java editor.

Same here and I don’t use any lsp4e editor.

Rather than arguing that JDT UI needs to adjust keybindings, I would assume lsp4e should define the binding in its own editor context and rely on CTRL 3 if that’s the binding of your choice.

**Comment by garretwilson** [comment]
Yes this is probably my most-used keystroke in Eclipse, using it many times daily for like 20 years. How can something just come in and break it for all of us across the IDE?

Instead of looking at workarounds, shouldn't the first order of business for such a crucial feature be: That Thing that was done to break this in Eclipse 2022-12? Well, stop doing That Thing and go back to the drawing board until someone can find a way to do That Thing without breaking the IDE.

I don't understand what crucial feature was added to the IDE that is so high-priority that it's suddenly OK that it breaks a core piece of day-to-day editing. Why should we have to add workarounds? Why was this ever acceptable? If it was broken, whatever broke it should be removed.

I'm not blaming anybody. I wouldn't know whom to blame. I don't even know what LSP4E is. And I'm sure everybody is working really hard to figure out What To Do. But conceptually, it seems simple: undo whatever broke this, unless That Thing has higher priority than day-to-day editing. What am I missing here? Is That Thing such a crucial feature that it has higher priority than the core editing keystrokes?

**Comment by trancexpress** [comment]
> I don't even know what LSP4E is.

Maybe you can remove/avoid lsp4e in your workflow. Personally I download the Eclipse SDK and install extra plug-ins on top (via: https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/releng/org.eclipse.ui.releng/platformUiTools.p2f )

This avoids installing/having lsp4e and is enough for me to work with Java and Eclipse plug-ins. Probably not a "solution" for many, of course.

**Comment by garretwilson** [comment]
But I am downloading the bare Eclipse EE ZIP file, unzipping it, and running it as I have done for years. What is this thing to remove from my workflow? It must be part of the bare Eclipse EE ZIP file, because that's what I'm using. And that's why I don't get it. Stop putting whatever is causing this problem in the bare Eclipse EE ZIP file until someone figures out how to do it without breaking Eclipse.

**Comment by mickaelistria** [comment]
@garretwilson The topic of the quality of the packages, how well they're tested or not, whether what they contains fit the audience...  must be discussed with the EPP project, this is not something Eclipse Platform is responsible for.

Here, there are actually 3 different bugs that have led to the same symptom. 1 was fixed in LSP4E some time ago (incorrect enablement condition), 1 is JDT being too open to such collision (for which https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/476 is a solution) and another is that handlers are reported as enabled when plugin is not active; which is something that may be a bit of Platform's fault, and a bit of LSP4E fault which https://github.com/eclipse/lsp4e/pull/551 attempts to fix.
