### ISSUE TITLE
Javadoc issues in generated code

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.ui#572]
As can be seen at https://download.eclipse.org/eclipse/downloads/drops4/I20230208-1800/compilelogs/platform.doc.isv.javadoc.txt :
```
../../../eclipse.platform.ui/bundles/org.eclipse.e4.ui.model.workbench/src/org/eclipse/e4/ui/model/application/ui/basic/MPart.java:182: error: unexpected end tag: </p>
	 * </p>
	   ^
../../../eclipse.platform.ui/bundles/org.eclipse.e4.ui.model.workbench/src/org/eclipse/e4/ui/model/application/descriptor/basic/MPartDescriptor.java:340: error: unexpected end tag: </p>
	 * </p>
	   ^
../../../eclipse.platform.ui/bundles/org.eclipse.e4.ui.model.workbench/src/org/eclipse/e4/ui/model/application/ui/advanced/MPerspective.java:82: error: unexpected end tag: </p>
	 * </p>
	   ^
3 errors
```

**Comment by akurtakov** [comment]
@merks These were fine before regenerating the code yesterday so what should be done here?

**Comment by merks** [comment]
Let's see...

**Comment by merks** [comment]
@akurtakov 

It is complaining because the `@since` is within the `<p></p>`?

![image](https://user-images.githubusercontent.com/208716/217755346-53e459db-9b73-4b4e-bdba-c8cc858c0bf8.png)

It's specified that way in the model:

![image](https://user-images.githubusercontent.com/208716/217755577-be534729-0e97-4777-8e2d-f15619a6acaa.png)

Perhaps someone manually fixed it in the *.java but not in the model...

I just want to be sure I fix the right thing the right way so confirmation of what exact is wrong would be helpful.  I'm guessing assuming it's the nesting in the paragraph that's wrong...

**Comment by laeubi** [comment]
@akurtakov I think I added javadoc generation as part of the verification build in equinox mabye would be usefull for platform.ui as well?

**Comment by akurtakov** [comment]
Yes, that should be the complain as looking at https://github.com/eclipse-platform/eclipse.platform.ui/commit/240f86f55cea7cf954c059d187ed66c6f721f822 points exactly these changes @since going inside the paragraph.

**Comment by akurtakov** [comment]
> @akurtakov I think I added javadoc generation as part of the verification build in equinox mabye would be usefull for platform.ui as well?

That would be really welcome!

**Comment by merks** [comment]
Even the generator extracts the `@since` from the model doc and expects it at the end so it was extracting the `</p>` and generating that in other places, e.g., the generated package.  But I guess Javadoc isn't generated for the generated package Impls....
