### ISSUE TITLE
Change in Onboarding commands are not adapted

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#675]
If I add a new onboarding command to a perspective, I need to clean the workspace to see it.

@marcushoepfner can you have a look?

**Comment by marcushoepfner** [comment]
Not exactly. The command (and also the text and image uri) are stored in the "tags" element of MPerspective.
AFAIK this is saved in workpace.xmi file after closing the workbench. Next time, the workbench is started, just this file is read, no matter if commands have changed.
According to @BeckerWdf this also happens if icons are changed (e.g. a perspective icon).

During my testing I found out, that switching perspectives and/or resetting perspectives should also help.

I hope that onboarding information is changed occassionally. Furthermore I talked to some guys and they haven't seen their editor area empty for quite a long time (holds true for me too :) ).

So the question is, whether we really need to change something here...

**Comment by vogella** [comment]
But is PerspectiveExtensionReader not running at every startup? I could just remove the existing onboarding tags and re-added the new ones.

**Comment by vogella** [comment]
Stale model data can create multiple issues:
1.) Users installs new plugin with onboarding contribution -> not shown
2.) Users uninstall new plug-in with onboarding contribution -> still shown 
3.) Users changes key binding -> wrong keybinding shown

We had issues in the past for stale menu and toolbar entries and growing stale Part Descriptors which is why I had to write ModelCleanupAddon to remove such "dead" model entries.

**Comment by BeckerWdf** [comment]
> Stale model data can create multiple issues: 1.) Users installs new plugin with onboarding contribution -> not shown 2.) Users uninstall new plug-in with onboarding contribution -> still shown 3.) Users changes key binding -> wrong keybinding shown
> 
> We had issues in the past for stale menu and toolbar entries and growing stale Part Descriptors which is why I had to write ModelCleanupAddon to remove such "dead" model entries.

So what do you propose?

**Comment by vogella** [comment]
> > Stale model data can create multiple issues: 1.) Users installs new plugin with onboarding contribution -> not shown 2.) Users uninstall new plug-in with onboarding contribution -> still shown 3.) Users changes key binding -> wrong keybinding shown
> > We had issues in the past for stale menu and toolbar entries and growing stale Part Descriptors which is why I had to write ModelCleanupAddon to remove such "dead" model entries.
> 
> So what do you propose?

To handled it in PerspectiveExtensionReader if possible as said in https://github.com/eclipse-platform/eclipse.platform.ui/issues/675#issuecomment-1491676178

**Comment by marcushoepfner** [comment]
Fixed by https://github.com/eclipse-platform/eclipse.platform.ui/pull/685
