### ISSUE TITLE
Expand all / Collapse all takes very long in the search view if we have lots of search results

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#887]
Just noted at a client machine that if you have lots of search results and press the Expand all / Collapse all buttons Eclipse takes very very long to react. 

To test:

Import lots of projects
Search for something which is present a lot of times, e.g. the letter "a"
Press Expand all -> Wait cursor for a very long time
Press Collapse all -> Wait cursor for a long time

Would be nice to not block the UI here, or to be faster in the tree.

**Comment by merks** [comment]
This operation operates on the widgets and must happen in the UI thread.  

In EMF, because we support expand-all in general tree views where the tree might even be infinite, we do expansion with a timeout:

org.eclipse.emf.edit.ui.action.ExpandAllAction.expandAll(TreeViewer, long)

**Comment by jukzi** [comment]
may relate to https://github.com/eclipse-platform/eclipse.platform.swt/issues/901

**Comment by jukzi** [comment]
> org.eclipse.emf.edit.ui.action.ExpandAllAction.expandAll(TreeViewer, long)

https://github.com/eclipse-emf/org.eclipse.emf/blob/152362d7ef34e9e823678c979c8f1122d51853ec/plugins/org.eclipse.emf.edit.ui/src/org/eclipse/emf/edit/ui/action/ExpandAllAction.java#L259

**Comment by jukzi** [comment]
@vogella you need to give a concrete example. I just expanded 1 Million results in ~27 sec, which i think is a fair amount, since already the search took long.
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/757edbe2-430c-4891-8734-4c9709cb1034)
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/9ff93b2b-0532-4978-b43b-6b57ae98ac2c)

**Comment by jukzi** [comment]
Closing as not enough information provided. Please reopen with reproducer if any.
